(* This file was auto generated *)
type t = | CI_hacky of string * int | CI_default of string

let from6159 =
                                                            let ans = Hashtbl.create 1000 in
                                                            Hashtbl.add ans "RISCV_PACK" (CI_hacky ("ZBKB_RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_BCLR" (CI_hacky ("ZBS_RTYPE", 3));
                                                            Hashtbl.add ans "F_UN_TYPE_D" (CI_default "F_UN_TYPE_D");
                                                            Hashtbl.add ans "F_UN_TYPE_D" (CI_default "F_UN_TYPE_D");
                                                            Hashtbl.add ans "F_UN_TYPE_D" (CI_default "F_UN_TYPE_D");
                                                            Hashtbl.add ans "C_LH" (CI_default "C_LH");
                                                            Hashtbl.add ans "RISCV_REV8" (CI_default "RISCV_REV8");
                                                            Hashtbl.add ans "RISCV_ROLW" (CI_hacky ("ZBB_RTYPEW", 3));
                                                            Hashtbl.add ans "C_NOP_HINT" (CI_default "C_NOP_HINT");
                                                            Hashtbl.add ans "WXTYPE" (CI_default "WXTYPE");
                                                            Hashtbl.add ans "VFIRST_M" (CI_default "VFIRST_M");
                                                            Hashtbl.add ans "C_SRLI_HINT" (CI_default "C_SRLI_HINT");
                                                            Hashtbl.add ans "MVVMATYPE" (CI_default "MVVMATYPE");
                                                            Hashtbl.add ans "AES64DS" (CI_default "AES64DS");
                                                            Hashtbl.add ans "FENCEI_RESERVED" (CI_default "FENCEI_RESERVED");
                                                            Hashtbl.add ans "C_ADDI" (CI_default "C_ADDI");
                                                            Hashtbl.add ans "VMSBF_M" (CI_default "VMSBF_M");
                                                            Hashtbl.add ans "VLOXSEGTYPE" (CI_default "VLOXSEGTYPE");
                                                            Hashtbl.add ans "VFMERGE" (CI_default "VFMERGE");
                                                            Hashtbl.add ans "RIVVTYPE" (CI_default "RIVVTYPE");
                                                            Hashtbl.add ans "RISCV_SRAIW" (CI_hacky ("SHIFTIWOP", 3));
                                                            Hashtbl.add ans "MUL" (CI_default "MUL");
                                                            Hashtbl.add ans "C_ZEXT_W" (CI_default "C_ZEXT_W");
                                                            Hashtbl.add ans "SFENCE_INVAL_IR" (CI_default "SFENCE_INVAL_IR");
                                                            Hashtbl.add ans "RISCV_XPERM4" (CI_default "RISCV_XPERM4");
                                                            Hashtbl.add ans "VMSOF_M" (CI_default "VMSOF_M");
                                                            Hashtbl.add ans "C_AND" (CI_default "C_AND");
                                                            Hashtbl.add ans "AES32DSI" (CI_default "AES32DSI");
                                                            Hashtbl.add ans "RISCV_FLEQ_D" (CI_default "RISCV_FLEQ_D");
                                                            Hashtbl.add ans "RISCV_JALR" (CI_default "RISCV_JALR");
                                                            Hashtbl.add ans "RISCV_RORI" (CI_default "RISCV_RORI");
                                                            Hashtbl.add ans "AMOSWAP" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "VSSSEGTYPE" (CI_default "VSSSEGTYPE");
                                                            Hashtbl.add ans "VXTYPE" (CI_default "VXTYPE");
                                                            Hashtbl.add ans "VMSIF_M" (CI_default "VMSIF_M");
                                                            Hashtbl.add ans "FNMADD_S" (CI_hacky ("F_MADD_TYPE_S", 5));
                                                            Hashtbl.add ans "LOAD" (CI_default "LOAD");
                                                            Hashtbl.add ans "RISCV_ORI" (CI_hacky ("ITYPE", 3));
                                                            Hashtbl.add ans "VLSSEGTYPE" (CI_default "VLSSEGTYPE");
                                                            Hashtbl.add ans "VIOTA_M" (CI_default "VIOTA_M");
                                                            Hashtbl.add ans "SHA512SIG1H" (CI_default "SHA512SIG1H");
                                                            Hashtbl.add ans "RISCV_CLMULR" (CI_default "RISCV_CLMULR");
                                                            Hashtbl.add ans "RISCV_FLTQ_S" (CI_default "RISCV_FLTQ_S");
                                                            Hashtbl.add ans "RISCV_SLTIU" (CI_hacky ("ITYPE", 3));
                                                            Hashtbl.add ans "VXMSTYPE" (CI_default "VXMSTYPE");
                                                            Hashtbl.add ans "RISCV_CLZ" (CI_default "RISCV_CLZ");
                                                            Hashtbl.add ans "RISCV_MAX" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "VXSG" (CI_default "VXSG");
                                                            Hashtbl.add ans "RISCV_CLMULH" (CI_default "RISCV_CLMULH");
                                                            Hashtbl.add ans "RISCV_FLI_H" (CI_default "RISCV_FLI_H");
                                                            Hashtbl.add ans "FMADD_S" (CI_hacky ("F_MADD_TYPE_S", 5));
                                                            Hashtbl.add ans "VXCMPTYPE" (CI_default "VXCMPTYPE");
                                                            Hashtbl.add ans "VSETVLI" (CI_default "VSETVLI");
                                                            Hashtbl.add ans "C_LHU" (CI_default "C_LHU");
                                                            Hashtbl.add ans "RISCV_JAL" (CI_default "RISCV_JAL");
                                                            Hashtbl.add ans "C_SEXT_B" (CI_default "C_SEXT_B");
                                                            Hashtbl.add ans "ECALL" (CI_default "ECALL");
                                                            Hashtbl.add ans "RISCV_XORI" (CI_hacky ("ITYPE", 3));
                                                            Hashtbl.add ans "VLUXSEGTYPE" (CI_default "VLUXSEGTYPE");
                                                            Hashtbl.add ans "SHA512SUM1R" (CI_default "SHA512SUM1R");
                                                            Hashtbl.add ans "RISCV_BEXT" (CI_hacky ("ZBS_RTYPE", 3));
                                                            Hashtbl.add ans "C_FSWSP" (CI_default "C_FSWSP");
                                                            Hashtbl.add ans "RISCV_XOR" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "VITYPE" (CI_default "VITYPE");
                                                            Hashtbl.add ans "STORECON" (CI_default "STORECON");
                                                            Hashtbl.add ans "RISCV_SLLIW" (CI_hacky ("SHIFTIWOP", 3));
                                                            Hashtbl.add ans "VMVRTYPE" (CI_default "VMVRTYPE");
                                                            Hashtbl.add ans "VMVXS" (CI_default "VMVXS");
                                                            Hashtbl.add ans "VISG" (CI_default "VISG");
                                                            Hashtbl.add ans "RISCV_ANDN" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_SH2ADDUW" (CI_hacky ("ZBA_RTYPEUW", 3));
                                                            Hashtbl.add ans "C_FLD" (CI_default "C_FLD");
                                                            Hashtbl.add ans "RISCV_SLLI" (CI_hacky ("SHIFTIOP", 3));
                                                            Hashtbl.add ans "RISCV_UNZIP" (CI_default "RISCV_UNZIP");
                                                            Hashtbl.add ans "FADD_S" (CI_hacky ("F_BIN_RM_TYPE_S", 4));
                                                            Hashtbl.add ans "RISCV_SLLW" (CI_hacky ("RTYPEW", 3));
                                                            Hashtbl.add ans "SHA512SIG1" (CI_default "SHA512SIG1");
                                                            Hashtbl.add ans "RISCV_BLTU" (CI_hacky ("BTYPE", 3));
                                                            Hashtbl.add ans "RISCV_SH1ADDUW" (CI_hacky ("ZBA_RTYPEUW", 3));
                                                            Hashtbl.add ans "NITYPE" (CI_default "NITYPE");
                                                            Hashtbl.add ans "RISCV_BLT" (CI_hacky ("BTYPE", 3));
                                                            Hashtbl.add ans "C_ADD" (CI_default "C_ADD");
                                                            Hashtbl.add ans "RISCV_LUI" (CI_hacky ("UTYPE", 2));
                                                            Hashtbl.add ans "FVFTYPE" (CI_default "FVFTYPE");
                                                            Hashtbl.add ans "RISCV_SLL" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "WFI" (CI_default "WFI");
                                                            Hashtbl.add ans "VVMTYPE" (CI_default "VVMTYPE");
                                                            Hashtbl.add ans "MVXMATYPE" (CI_default "MVXMATYPE");
                                                            Hashtbl.add ans "RISCV_FLI_D" (CI_default "RISCV_FLI_D");
                                                            Hashtbl.add ans "C_ADDI_HINT" (CI_default "C_ADDI_HINT");
                                                            Hashtbl.add ans "RISCV_BNE" (CI_hacky ("BTYPE", 3));
                                                            Hashtbl.add ans "MASKTYPEX" (CI_default "MASKTYPEX");
                                                            Hashtbl.add ans "RISCV_BINVI" (CI_hacky ("ZBS_IOP", 3));
                                                            Hashtbl.add ans "RISCV_BCLRI" (CI_hacky ("ZBS_IOP", 3));
                                                            Hashtbl.add ans "RISCV_FROUNDNX_D" (CI_default "RISCV_FROUNDNX_D");
                                                            Hashtbl.add ans "RISCV_FROUND_D" (CI_default "RISCV_FROUND_D");
                                                            Hashtbl.add ans "FNMADD_D" (CI_hacky ("F_MADD_TYPE_D", 5));
                                                            Hashtbl.add ans "FENCE_RESERVED" (CI_default "FENCE_RESERVED");
                                                            Hashtbl.add ans "MASKTYPEI" (CI_default "MASKTYPEI");
                                                            Hashtbl.add ans "VSETIVLI" (CI_default "VSETIVLI");
                                                            Hashtbl.add ans "FVVTYPE" (CI_default "FVVTYPE");
                                                            Hashtbl.add ans "RISCV_CPOPW" (CI_default "RISCV_CPOPW");
                                                            Hashtbl.add ans "RISCV_FMAXM_D" (CI_default "RISCV_FMAXM_D");
                                                            Hashtbl.add ans "C_SD" (CI_default "C_SD");
                                                            Hashtbl.add ans "RISCV_ADDI" (CI_hacky ("ITYPE", 3));
                                                            Hashtbl.add ans "C_LI_HINT" (CI_default "C_LI_HINT");
                                                            Hashtbl.add ans "RISCV_RORW" (CI_hacky ("ZBB_RTYPEW", 3));
                                                            Hashtbl.add ans "FMUL_D" (CI_hacky ("F_BIN_RM_TYPE_D", 4));
                                                            Hashtbl.add ans "RISCV_SRAW" (CI_hacky ("RTYPEW", 3));
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "F_BIN_TYPE_H" (CI_default "F_BIN_TYPE_H");
                                                            Hashtbl.add ans "FMSUB_D" (CI_hacky ("F_MADD_TYPE_D", 5));
                                                            Hashtbl.add ans "SHA256SUM1" (CI_default "SHA256SUM1");
                                                            Hashtbl.add ans "VSUXSEGTYPE" (CI_default "VSUXSEGTYPE");
                                                            Hashtbl.add ans "ZBKB_PACKW" (CI_default "ZBKB_PACKW");
                                                            Hashtbl.add ans "RISCV_SH3ADDUW" (CI_hacky ("ZBA_RTYPEUW", 3));
                                                            Hashtbl.add ans "FVVMTYPE" (CI_default "FVVMTYPE");
                                                            Hashtbl.add ans "VMVSX" (CI_default "VMVSX");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_D" (CI_default "F_UN_RM_TYPE_D");
                                                            Hashtbl.add ans "RISCV_ORCB" (CI_default "RISCV_ORCB");
                                                            Hashtbl.add ans "VIMCTYPE" (CI_default "VIMCTYPE");
                                                            Hashtbl.add ans "RISCV_SUBW" (CI_hacky ("RTYPEW", 3));
                                                            Hashtbl.add ans "VIMSTYPE" (CI_default "VIMSTYPE");
                                                            Hashtbl.add ans "MASKTYPEV" (CI_default "MASKTYPEV");
                                                            Hashtbl.add ans "C_MUL" (CI_default "C_MUL");
                                                            Hashtbl.add ans "AMOXOR" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "FVFMTYPE" (CI_default "FVFMTYPE");
                                                            Hashtbl.add ans "SM3P1" (CI_default "SM3P1");
                                                            Hashtbl.add ans "RISCV_CLMUL" (CI_default "RISCV_CLMUL");
                                                            Hashtbl.add ans "ADDIW" (CI_default "ADDIW");
                                                            Hashtbl.add ans "RISCV_FLEQ_S" (CI_default "RISCV_FLEQ_S");
                                                            Hashtbl.add ans "RISCV_SH3ADD" (CI_hacky ("ZBA_RTYPE", 3));
                                                            Hashtbl.add ans "MRET" (CI_default "MRET");
                                                            Hashtbl.add ans "WVXTYPE" (CI_default "WVXTYPE");
                                                            Hashtbl.add ans "RISCV_FMAXM_S" (CI_default "RISCV_FMAXM_S");
                                                            Hashtbl.add ans "AMOMAXU" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "C_ILLEGAL" (CI_default "C_ILLEGAL");
                                                            Hashtbl.add ans "VLSEGFFTYPE" (CI_default "VLSEGFFTYPE");
                                                            Hashtbl.add ans "C_ANDI" (CI_default "C_ANDI");
                                                            Hashtbl.add ans "FMUL_H" (CI_hacky ("F_BIN_RM_TYPE_H", 4));
                                                            Hashtbl.add ans "RISCV_SEXTB" (CI_hacky ("ZBB_EXTOP", 2));
                                                            Hashtbl.add ans "NXSTYPE" (CI_default "NXSTYPE");
                                                            Hashtbl.add ans "RISCV_SH1ADD" (CI_hacky ("ZBA_RTYPE", 3));
                                                            Hashtbl.add ans "VSOXSEGTYPE" (CI_default "VSOXSEGTYPE");
                                                            Hashtbl.add ans "WVTYPE" (CI_default "WVTYPE");
                                                            Hashtbl.add ans "C_SDSP" (CI_default "C_SDSP");
                                                            Hashtbl.add ans "C_NOP" (CI_default "C_NOP");
                                                            Hashtbl.add ans "VXMCTYPE" (CI_default "VXMCTYPE");
                                                            Hashtbl.add ans "MMTYPE" (CI_default "MMTYPE");
                                                            Hashtbl.add ans "C_SUBW" (CI_default "C_SUBW");
                                                            Hashtbl.add ans "VEXT4TYPE" (CI_default "VEXT4TYPE");
                                                            Hashtbl.add ans "VSETVL" (CI_default "VSETVL");
                                                            Hashtbl.add ans "C_SH" (CI_default "C_SH");
                                                            Hashtbl.add ans "FNMSUB_S" (CI_hacky ("F_MADD_TYPE_S", 5));
                                                            Hashtbl.add ans "MVVCOMPRESS" (CI_default "MVVCOMPRESS");
                                                            Hashtbl.add ans "F_UN_TYPE_S" (CI_default "F_UN_TYPE_S");
                                                            Hashtbl.add ans "F_UN_TYPE_S" (CI_default "F_UN_TYPE_S");
                                                            Hashtbl.add ans "F_UN_TYPE_S" (CI_default "F_UN_TYPE_S");
                                                            Hashtbl.add ans "RISCV_SLT" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "FWVVTYPE" (CI_default "FWVVTYPE");
                                                            Hashtbl.add ans "RISCV_FROUND_H" (CI_default "RISCV_FROUND_H");
                                                            Hashtbl.add ans "RISCV_ADD" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "C_JAL" (CI_default "C_JAL");
                                                            Hashtbl.add ans "SFENCE_VMA" (CI_default "SFENCE_VMA");
                                                            Hashtbl.add ans "NVTYPE" (CI_default "NVTYPE");
                                                            Hashtbl.add ans "RISCV_ANDI" (CI_hacky ("ITYPE", 3));
                                                            Hashtbl.add ans "AES64KS2" (CI_default "AES64KS2");
                                                            Hashtbl.add ans "RISCV_SRA" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_BEQ" (CI_hacky ("BTYPE", 3));
                                                            Hashtbl.add ans "NVSTYPE" (CI_default "NVSTYPE");
                                                            Hashtbl.add ans "RISCV_MINU" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "FMUL_S" (CI_hacky ("F_BIN_RM_TYPE_S", 4));
                                                            Hashtbl.add ans "RISCV_BINV" (CI_hacky ("ZBS_RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_AND" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_BGE" (CI_hacky ("BTYPE", 3));
                                                            Hashtbl.add ans "RISCV_FROUND_S" (CI_default "RISCV_FROUND_S");
                                                            Hashtbl.add ans "RISCV_MAXU" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "NISTYPE" (CI_default "NISTYPE");
                                                            Hashtbl.add ans "C_SLLI" (CI_default "C_SLLI");
                                                            Hashtbl.add ans "AES32ESMI" (CI_default "AES32ESMI");
                                                            Hashtbl.add ans "VXMTYPE" (CI_default "VXMTYPE");
                                                            Hashtbl.add ans "RISCV_SRAI" (CI_hacky ("SHIFTIOP", 3));
                                                            Hashtbl.add ans "FMADD_H" (CI_hacky ("F_MADD_TYPE_H", 5));
                                                            Hashtbl.add ans "FENCEI" (CI_default "FENCEI");
                                                            Hashtbl.add ans "RISCV_FROUNDNX_H" (CI_default "RISCV_FROUNDNX_H");
                                                            Hashtbl.add ans "VFMVSF" (CI_default "VFMVSF");
                                                            Hashtbl.add ans "MOVETYPEI" (CI_default "MOVETYPEI");
                                                            Hashtbl.add ans "RISCV_OR" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_FLTQ_H" (CI_default "RISCV_FLTQ_H");
                                                            Hashtbl.add ans "VEXT8TYPE" (CI_default "VEXT8TYPE");
                                                            Hashtbl.add ans "C_OR" (CI_default "C_OR");
                                                            Hashtbl.add ans "C_LW" (CI_default "C_LW");
                                                            Hashtbl.add ans "FWVFMATYPE" (CI_default "FWVFMATYPE");
                                                            Hashtbl.add ans "C_LWSP" (CI_default "C_LWSP");
                                                            Hashtbl.add ans "C_ADDI16SP" (CI_default "C_ADDI16SP");
                                                            Hashtbl.add ans "SHA512SIG0L" (CI_default "SHA512SIG0L");
                                                            Hashtbl.add ans "SM3P0" (CI_default "SM3P0");
                                                            Hashtbl.add ans "SM4ED" (CI_default "SM4ED");
                                                            Hashtbl.add ans "RISCV_FMINM_D" (CI_default "RISCV_FMINM_D");
                                                            Hashtbl.add ans "AES64IM" (CI_default "AES64IM");
                                                            Hashtbl.add ans "DIVW" (CI_default "DIVW");
                                                            Hashtbl.add ans "RISCV_SLTU" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "VLRETYPE" (CI_default "VLRETYPE");
                                                            Hashtbl.add ans "C_ZEXT_B" (CI_default "C_ZEXT_B");
                                                            Hashtbl.add ans "C_MV" (CI_default "C_MV");
                                                            Hashtbl.add ans "VIMTYPE" (CI_default "VIMTYPE");
                                                            Hashtbl.add ans "VFMVFS" (CI_default "VFMVFS");
                                                            Hashtbl.add ans "LOADRES" (CI_default "LOADRES");
                                                            Hashtbl.add ans "RISCV_SRL" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_CTZ" (CI_default "RISCV_CTZ");
                                                            Hashtbl.add ans "C_J" (CI_default "C_J");
                                                            Hashtbl.add ans "AMOMINU" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "AES32ESI" (CI_default "AES32ESI");
                                                            Hashtbl.add ans "RISCV_FMVH_X_D" (CI_default "RISCV_FMVH_X_D");
                                                            Hashtbl.add ans "RISCV_SLLIUW" (CI_default "RISCV_SLLIUW");
                                                            Hashtbl.add ans "C_BEQZ" (CI_default "C_BEQZ");
                                                            Hashtbl.add ans "FDIV_H" (CI_hacky ("F_BIN_RM_TYPE_H", 4));
                                                            Hashtbl.add ans "AMOMAX" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "RISCV_SRLW" (CI_hacky ("RTYPEW", 3));
                                                            Hashtbl.add ans "SHA512SUM0" (CI_default "SHA512SUM0");
                                                            Hashtbl.add ans "RISCV_FMINM_S" (CI_default "RISCV_FMINM_S");
                                                            Hashtbl.add ans "SHA512SUM0R" (CI_default "SHA512SUM0R");
                                                            Hashtbl.add ans "C_ADD_HINT" (CI_default "C_ADD_HINT");
                                                            Hashtbl.add ans "REMW" (CI_default "REMW");
                                                            Hashtbl.add ans "VFMV" (CI_default "VFMV");
                                                            Hashtbl.add ans "RISCV_ZIP" (CI_default "RISCV_ZIP");
                                                            Hashtbl.add ans "C_SEXT_H" (CI_default "C_SEXT_H");
                                                            Hashtbl.add ans "SHA512SUM1" (CI_default "SHA512SUM1");
                                                            Hashtbl.add ans "FDIV_S" (CI_hacky ("F_BIN_RM_TYPE_S", 4));
                                                            Hashtbl.add ans "CSRRW" (CI_hacky ("CSR", 4));
                                                            Hashtbl.add ans "WMVXTYPE" (CI_default "WMVXTYPE");
                                                            Hashtbl.add ans "FNMSUB_H" (CI_hacky ("F_MADD_TYPE_H", 5));
                                                            Hashtbl.add ans "C_LDSP" (CI_default "C_LDSP");
                                                            Hashtbl.add ans "RISCV_BGEU" (CI_hacky ("BTYPE", 3));
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_H" (CI_default "F_UN_RM_TYPE_H");
                                                            Hashtbl.add ans "RISCV_CPOP" (CI_default "RISCV_CPOP");
                                                            Hashtbl.add ans "C_FSW" (CI_default "C_FSW");
                                                            Hashtbl.add ans "C_SW" (CI_default "C_SW");
                                                            Hashtbl.add ans "FADD_H" (CI_hacky ("F_BIN_RM_TYPE_H", 4));
                                                            Hashtbl.add ans "FWFTYPE" (CI_default "FWFTYPE");
                                                            Hashtbl.add ans "FMADD_D" (CI_hacky ("F_MADD_TYPE_D", 5));
                                                            Hashtbl.add ans "C_SUB" (CI_default "C_SUB");
                                                            Hashtbl.add ans "VFUNARY0" (CI_default "VFUNARY0");
                                                            Hashtbl.add ans "FWVTYPE" (CI_default "FWVTYPE");
                                                            Hashtbl.add ans "FMSUB_S" (CI_hacky ("F_MADD_TYPE_S", 5));
                                                            Hashtbl.add ans "RISCV_FROUNDNX_S" (CI_default "RISCV_FROUNDNX_S");
                                                            Hashtbl.add ans "SM4KS" (CI_default "SM4KS");
                                                            Hashtbl.add ans "RISCV_RORIW" (CI_default "RISCV_RORIW");
                                                            Hashtbl.add ans "SFENCE_W_INVAL" (CI_default "SFENCE_W_INVAL");
                                                            Hashtbl.add ans "C_JR" (CI_default "C_JR");
                                                            Hashtbl.add ans "NXTYPE" (CI_default "NXTYPE");
                                                            Hashtbl.add ans "C_NOT" (CI_default "C_NOT");
                                                            Hashtbl.add ans "FNMSUB_D" (CI_hacky ("F_MADD_TYPE_D", 5));
                                                            Hashtbl.add ans "MVVTYPE" (CI_default "MVVTYPE");
                                                            Hashtbl.add ans "C_ADDIW" (CI_default "C_ADDIW");
                                                            Hashtbl.add ans "C_LD" (CI_default "C_LD");
                                                            Hashtbl.add ans "FVFMATYPE" (CI_default "FVFMATYPE");
                                                            Hashtbl.add ans "RISCV_CTZW" (CI_default "RISCV_CTZW");
                                                            Hashtbl.add ans "RISCV_SRLIW" (CI_hacky ("SHIFTIWOP", 3));
                                                            Hashtbl.add ans "RISCV_XPERM8" (CI_default "RISCV_XPERM8");
                                                            Hashtbl.add ans "RISCV_FMAXM_H" (CI_default "RISCV_FMAXM_H");
                                                            Hashtbl.add ans "FSUB_H" (CI_hacky ("F_BIN_RM_TYPE_H", 4));
                                                            Hashtbl.add ans "RISCV_ADDUW" (CI_hacky ("ZBA_RTYPEUW", 3));
                                                            Hashtbl.add ans "SHA256SUM0" (CI_default "SHA256SUM0");
                                                            Hashtbl.add ans "C_XOR" (CI_default "C_XOR");
                                                            Hashtbl.add ans "VID_V" (CI_default "VID_V");
                                                            Hashtbl.add ans "FENCE" (CI_default "FENCE");
                                                            Hashtbl.add ans "RISCV_CZERO_NEZ" (CI_hacky ("ZICOND_RTYPE", 4));
                                                            Hashtbl.add ans "RISCV_CZERO_EQZ" (CI_hacky ("ZICOND_RTYPE", 4));
                                                            Hashtbl.add ans "C_FLWSP" (CI_default "C_FLWSP");
                                                            Hashtbl.add ans "STORE" (CI_default "STORE");
                                                            Hashtbl.add ans "RISCV_FMINM_H" (CI_default "RISCV_FMINM_H");
                                                            Hashtbl.add ans "C_LUI_HINT" (CI_default "C_LUI_HINT");
                                                            Hashtbl.add ans "VVMCTYPE" (CI_default "VVMCTYPE");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "F_BIN_TYPE_S" (CI_default "F_BIN_TYPE_S");
                                                            Hashtbl.add ans "VSSEGTYPE" (CI_default "VSSEGTYPE");
                                                            Hashtbl.add ans "SINVAL_VMA" (CI_default "SINVAL_VMA");
                                                            Hashtbl.add ans "MOVETYPEX" (CI_default "MOVETYPEX");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "F_BIN_TYPE_D" (CI_default "F_BIN_TYPE_D");
                                                            Hashtbl.add ans "RISCV_ROL" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "AMOAND" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "C_FSDSP" (CI_default "C_FSDSP");
                                                            Hashtbl.add ans "C_BNEZ" (CI_default "C_BNEZ");
                                                            Hashtbl.add ans "SRET" (CI_default "SRET");
                                                            Hashtbl.add ans "FWVVMATYPE" (CI_default "FWVVMATYPE");
                                                            Hashtbl.add ans "AES64KS1I" (CI_default "AES64KS1I");
                                                            Hashtbl.add ans "STORE_FP" (CI_default "STORE_FP");
                                                            Hashtbl.add ans "C_JALR" (CI_default "C_JALR");
                                                            Hashtbl.add ans "RMVVTYPE" (CI_default "RMVVTYPE");
                                                            Hashtbl.add ans "AMOOR" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "RISCV_CLZW" (CI_default "RISCV_CLZW");
                                                            Hashtbl.add ans "REM" (CI_default "REM");
                                                            Hashtbl.add ans "C_EBREAK" (CI_default "C_EBREAK");
                                                            Hashtbl.add ans "FENCE_TSO" (CI_default "FENCE_TSO");
                                                            Hashtbl.add ans "RISCV_SLTI" (CI_hacky ("ITYPE", 3));
                                                            Hashtbl.add ans "SHA512SIG0" (CI_default "SHA512SIG0");
                                                            Hashtbl.add ans "AES64ESM" (CI_default "AES64ESM");
                                                            Hashtbl.add ans "RISCV_FLI_S" (CI_default "RISCV_FLI_S");
                                                            Hashtbl.add ans "C_SB" (CI_default "C_SB");
                                                            Hashtbl.add ans "C_FLDSP" (CI_default "C_FLDSP");
                                                            Hashtbl.add ans "C_MV_HINT" (CI_default "C_MV_HINT");
                                                            Hashtbl.add ans "VFNUNARY0" (CI_default "VFNUNARY0");
                                                            Hashtbl.add ans "RISCV_AUIPC" (CI_hacky ("UTYPE", 2));
                                                            Hashtbl.add ans "VFWUNARY0" (CI_default "VFWUNARY0");
                                                            Hashtbl.add ans "MOVETYPEV" (CI_default "MOVETYPEV");
                                                            Hashtbl.add ans "RISCV_SEXTH" (CI_hacky ("ZBB_EXTOP", 2));
                                                            Hashtbl.add ans "RISCV_SH2ADD" (CI_hacky ("ZBA_RTYPE", 3));
                                                            Hashtbl.add ans "VFUNARY1" (CI_default "VFUNARY1");
                                                            Hashtbl.add ans "FWVFTYPE" (CI_default "FWVFTYPE");
                                                            Hashtbl.add ans "RISCV_FCVTMOD_W_D" (CI_default "RISCV_FCVTMOD_W_D");
                                                            Hashtbl.add ans "C_SRLI" (CI_default "C_SRLI");
                                                            Hashtbl.add ans "RISCV_BSET" (CI_hacky ("ZBS_RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_ADDW" (CI_hacky ("RTYPEW", 3));
                                                            Hashtbl.add ans "RFVVTYPE" (CI_default "RFVVTYPE");
                                                            Hashtbl.add ans "VSRETYPE" (CI_default "VSRETYPE");
                                                            Hashtbl.add ans "RISCV_ORN" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "C_SLLI_HINT" (CI_default "C_SLLI_HINT");
                                                            Hashtbl.add ans "SHA512SIG0H" (CI_default "SHA512SIG0H");
                                                            Hashtbl.add ans "WVVTYPE" (CI_default "WVVTYPE");
                                                            Hashtbl.add ans "LOAD_FP" (CI_default "LOAD_FP");
                                                            Hashtbl.add ans "VVMSTYPE" (CI_default "VVMSTYPE");
                                                            Hashtbl.add ans "FVVMATYPE" (CI_default "FVVMATYPE");
                                                            Hashtbl.add ans "AES64DSM" (CI_default "AES64DSM");
                                                            Hashtbl.add ans "FDIV_D" (CI_hacky ("F_BIN_RM_TYPE_D", 4));
                                                            Hashtbl.add ans "VEXT2TYPE" (CI_default "VEXT2TYPE");
                                                            Hashtbl.add ans "URET" (CI_default "URET");
                                                            Hashtbl.add ans "C_LI" (CI_default "C_LI");
                                                            Hashtbl.add ans "EBREAK" (CI_default "EBREAK");
                                                            Hashtbl.add ans "FADD_D" (CI_hacky ("F_BIN_RM_TYPE_D", 4));
                                                            Hashtbl.add ans "C_SRAI" (CI_default "C_SRAI");
                                                            Hashtbl.add ans "RISCV_SRLI" (CI_hacky ("SHIFTIOP", 3));
                                                            Hashtbl.add ans "C_LUI" (CI_default "C_LUI");
                                                            Hashtbl.add ans "RISCV_FMVP_D_X" (CI_default "RISCV_FMVP_D_X");
                                                            Hashtbl.add ans "C_LBU" (CI_default "C_LBU");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "F_UN_RM_TYPE_S" (CI_default "F_UN_RM_TYPE_S");
                                                            Hashtbl.add ans "RISCV_ZEXTH" (CI_hacky ("ZBB_EXTOP", 2));
                                                            Hashtbl.add ans "RISCV_XNOR" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "RISCV_MIN" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "WMVVTYPE" (CI_default "WMVVTYPE");
                                                            Hashtbl.add ans "C_ZEXT_H" (CI_default "C_ZEXT_H");
                                                            Hashtbl.add ans "MULW" (CI_default "MULW");
                                                            Hashtbl.add ans "SHA512SIG1L" (CI_default "SHA512SIG1L");
                                                            Hashtbl.add ans "VVCMPTYPE" (CI_default "VVCMPTYPE");
                                                            Hashtbl.add ans "VLSEGTYPE" (CI_default "VLSEGTYPE");
                                                            Hashtbl.add ans "ILLEGAL" (CI_default "ILLEGAL");
                                                            Hashtbl.add ans "SHA256SIG0" (CI_default "SHA256SIG0");
                                                            Hashtbl.add ans "FSUB_D" (CI_hacky ("F_BIN_RM_TYPE_D", 4));
                                                            Hashtbl.add ans "RISCV_BREV8" (CI_default "RISCV_BREV8");
                                                            Hashtbl.add ans "RISCV_PACKH" (CI_hacky ("ZBKB_RTYPE", 3));
                                                            Hashtbl.add ans "AES32DSMI" (CI_default "AES32DSMI");
                                                            Hashtbl.add ans "F_UN_TYPE_H" (CI_default "F_UN_TYPE_H");
                                                            Hashtbl.add ans "F_UN_TYPE_H" (CI_default "F_UN_TYPE_H");
                                                            Hashtbl.add ans "F_UN_TYPE_H" (CI_default "F_UN_TYPE_H");
                                                            Hashtbl.add ans "RISCV_SUB" (CI_hacky ("RTYPE", 3));
                                                            Hashtbl.add ans "C_FSD" (CI_default "C_FSD");
                                                            Hashtbl.add ans "FSUB_S" (CI_hacky ("F_BIN_RM_TYPE_S", 4));
                                                            Hashtbl.add ans "C_ADDI4SPN" (CI_default "C_ADDI4SPN");
                                                            Hashtbl.add ans "C_ADDW" (CI_default "C_ADDW");
                                                            Hashtbl.add ans "RISCV_BEXTI" (CI_hacky ("ZBS_IOP", 3));
                                                            Hashtbl.add ans "VVTYPE" (CI_default "VVTYPE");
                                                            Hashtbl.add ans "FNMADD_H" (CI_hacky ("F_MADD_TYPE_H", 5));
                                                            Hashtbl.add ans "RISCV_BSETI" (CI_hacky ("ZBS_IOP", 3));
                                                            Hashtbl.add ans "VCPOP_M" (CI_default "VCPOP_M");
                                                            Hashtbl.add ans "FMSUB_H" (CI_hacky ("F_MADD_TYPE_H", 5));
                                                            Hashtbl.add ans "AMOADD" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "SHA256SIG1" (CI_default "SHA256SIG1");
                                                            Hashtbl.add ans "RISCV_FLEQ_H" (CI_default "RISCV_FLEQ_H");
                                                            Hashtbl.add ans "RISCV_ROR" (CI_hacky ("ZBB_RTYPE", 3));
                                                            Hashtbl.add ans "VICMPTYPE" (CI_default "VICMPTYPE");
                                                            Hashtbl.add ans "MVXTYPE" (CI_default "MVXTYPE");
                                                            Hashtbl.add ans "C_FLW" (CI_default "C_FLW");
                                                            Hashtbl.add ans "C_SWSP" (CI_default "C_SWSP");
                                                            Hashtbl.add ans "RISCV_FLTQ_D" (CI_default "RISCV_FLTQ_D");
                                                            Hashtbl.add ans "AMOMIN" (CI_hacky ("AMO", 0));
                                                            Hashtbl.add ans "AES64ES" (CI_default "AES64ES");
                                                            Hashtbl.add ans "C_SRAI_HINT" (CI_default "C_SRAI_HINT");
                                                            Hashtbl.add ans "DIV" (CI_default "DIV");
                                                            ans 
let from6159_hacky = [ "VMTYPE"; ]

