(* This file was auto generated *)
include From6159_helper

let from6159 =
  let ans = Hash_info.create 1000 in
  hacky ans "ZBKB_RTYPE" "RISCV_PACK" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBS_RTYPE" "RISCV_BCLR" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_UN_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_LH" {out=["rdc"]; inputs=["rs1c"]};
  def ans  "RISCV_REV8" {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBB_RTYPEW" "RISCV_ROLW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_NOP_HINT" {out=[]; inputs=[]};
  def ans  "WXTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "VFIRST_M" {out=["rd"]; inputs=[]};
  def ans  "C_SRLI_HINT" {out=[]; inputs=[]};
  def ans  "MVVMATYPE" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  def ans  "AES64DS" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "FENCEI_RESERVED" {out=[]; inputs=[]};
  def ans  "C_ADDI" {out=["rsd"]; inputs=["rsd"]};
  def ans  "VMSBF_M" {out=["vd"]; inputs=[]};
  def ans  "VLOXSEGTYPE" {out=["vd"]; inputs=[]};
  def ans  "VFMERGE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "RIVVTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  hacky ans "SHIFTIWOP" "RISCV_SRAIW" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "MUL" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_ZEXT_W" {out=["rsdc"]; inputs=["rsdc"]};
  def ans  "SFENCE_INVAL_IR" {out=[]; inputs=[]};
  def ans  "RISCV_XPERM4" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VMSOF_M" {out=["vd"]; inputs=[]};
  def ans  "C_AND" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  def ans  "AES32DSI" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "RISCV_FLEQ_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_JALR" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_RORI" {out=["rd"]; inputs=["rs1"]};
  hacky ans "AMO" "AMOSWAP" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VSSSEGTYPE" {out=[]; inputs=[]};
  def ans  "VXTYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "VMSIF_M" {out=["vd"]; inputs=[]};
  hacky ans "F_MADD_TYPE_S" "FNMADD_S" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "LOAD" {out=["rd"]; inputs=["rs1"]};
  hacky ans "ITYPE" "RISCV_ORI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "VLSSEGTYPE" {out=["vd"]; inputs=[]};
  def ans  "VIOTA_M" {out=["vd"]; inputs=["vd"]};
  def ans  "SHA512SIG1H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_CLMULR" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_FLTQ_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ITYPE" "RISCV_SLTIU" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "VXMSTYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "RISCV_CLZ" {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBB_RTYPE" "RISCV_MAX" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VXSG" {out=["vd"]; inputs=["vd"; "vs2"; "rs1"]};
  def ans  "RISCV_CLMULH" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_FLI_H" {out=["rd"]; inputs=[]};
  hacky ans "F_MADD_TYPE_S" "FMADD_S" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "VXCMPTYPE" {out=["vd"]; inputs=["vs2"]};
  def ans  "VSETVLI" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_LHU" {out=["rdc"]; inputs=["rs1c"]};
  def ans  "RISCV_JAL" {out=["rd"]; inputs=[]};
  def ans  "C_SEXT_B" {out=["rsdc"]; inputs=["rsdc"]};
  def ans  "ECALL" {out=[]; inputs=[]};
  hacky ans "ITYPE" "RISCV_XORI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "VLUXSEGTYPE" {out=["vd"]; inputs=[]};
  def ans  "SHA512SUM1R" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBS_RTYPE" "RISCV_BEXT" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_FSWSP" {out=[]; inputs=["sp"; "rs2"]};
  hacky ans "RTYPE" "RISCV_XOR" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VITYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "STORECON" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "SHIFTIWOP" "RISCV_SLLIW" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "VMVRTYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "VMVXS" {out=["rd"]; inputs=["vs2"]};
  def ans  "VISG" {out=["vd"]; inputs=["vd"; "vs2"]};
  hacky ans "ZBB_RTYPE" "RISCV_ANDN" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBA_RTYPEUW" "RISCV_SH2ADDUW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_FLD" {out=["rdc"]; inputs=["rsc"]};
  hacky ans "SHIFTIOP" "RISCV_SLLI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_UNZIP" {out=[]; inputs=[]};
  hacky ans "F_BIN_RM_TYPE_S" "FADD_S" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPEW" "RISCV_SLLW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SHA512SIG1" {out=["rd"]; inputs=["rs1"]};
  hacky ans "BTYPE" "RISCV_BLTU" 3 {out=[]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBA_RTYPEUW" "RISCV_SH1ADDUW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "NITYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  hacky ans "BTYPE" "RISCV_BLT" 3 {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "C_ADD" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  hacky ans "UTYPE" "RISCV_LUI" 2 {out=["rd"]; inputs=[]};
  def ans  "FVFTYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  hacky ans "RTYPE" "RISCV_SLL" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "WFI" {out=[]; inputs=[]};
  def ans  "VVMTYPE" {out=["vd"]; inputs=["vs2"; "vs1"]};
  def ans  "MVXMATYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "RISCV_FLI_D" {out=["rd"]; inputs=[]};
  def ans  "C_ADDI_HINT" {out=[]; inputs=[]};
  hacky ans "BTYPE" "RISCV_BNE" 3 {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "MASKTYPEX" {out=["vd"]; inputs=["vd"; "vs2"]};
  hacky ans "ZBS_IOP" "RISCV_BINVI" 3 {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBS_IOP" "RISCV_BCLRI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_FROUNDNX_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_FROUND_D" {out=["rd"]; inputs=["rs1"]};
  hacky ans "F_MADD_TYPE_D" "FNMADD_D" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "FENCE_RESERVED" {out=[]; inputs=[]};
  def ans  "MASKTYPEI" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "VSETIVLI" {out=["rd"]; inputs=[]};
  def ans  "FVVTYPE" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  def ans  "RISCV_CPOPW" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_FMAXM_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_SD" {out=[]; inputs=["rsc1"; "rsc2"]};
  hacky ans "ITYPE" "RISCV_ADDI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "C_LI_HINT" {out=[]; inputs=[]};
  hacky ans "ZBB_RTYPEW" "RISCV_RORW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "F_BIN_RM_TYPE_D" "FMUL_D" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPEW" "RISCV_SRAW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "F_MADD_TYPE_D" "FMSUB_D" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "SHA256SUM1" {out=["rd"]; inputs=["rs1"]};
  def ans  "VSUXSEGTYPE" {out=[]; inputs=[]};
  def ans  "ZBKB_PACKW" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBA_RTYPEUW" "RISCV_SH3ADDUW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "FVVMTYPE" {out=["vd"]; inputs=["vs2"; "vs1"]};
  def ans  "VMVSX" {out=["vd"]; inputs=["vd"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_ORCB" {out=["rd"]; inputs=["rs1"]};
  def ans  "VIMCTYPE" {out=["vd"]; inputs=["vs2"]};
  hacky ans "RTYPEW" "RISCV_SUBW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VIMSTYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "MASKTYPEV" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  def ans  "C_MUL" {out=["rsdc"]; inputs=["rsdc"; "rs2c"]};
  hacky ans "AMO" "AMOXOR" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "FVFMTYPE" {out=["vd"]; inputs=["vs2"]};
  def ans  "SM3P1" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_CLMUL" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "ADDIW" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_FLEQ_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBA_RTYPE" "RISCV_SH3ADD" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "MRET" {out=[]; inputs=[]};
  def ans  "WVXTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "RISCV_FMAXM_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "AMO" "AMOMAXU" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_ILLEGAL" {out=[]; inputs=[]};
  def ans  "VLSEGFFTYPE" {out=["vd"]; inputs=[]};
  def ans  "C_ANDI" {out=["rsd"]; inputs=["rsd"]};
  hacky ans "F_BIN_RM_TYPE_H" "FMUL_H" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBB_EXTOP" "RISCV_SEXTB" 2 {out=["rd"]; inputs=["rs1"]};
  def ans  "NXSTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  hacky ans "ZBA_RTYPE" "RISCV_SH1ADD" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VSOXSEGTYPE" {out=[]; inputs=[]};
  def ans  "WVTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  def ans  "C_SDSP" {out=[]; inputs=["sp"; "rs2"]};
  def ans  "C_NOP" {out=[]; inputs=[]};
  def ans  "VXMCTYPE" {out=["vd"]; inputs=["vs2"]};
  def ans  "MMTYPE" {out=["vd"]; inputs=[]};
  def ans  "C_SUBW" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  def ans  "VEXT4TYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "VSETVL" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "C_SH" {out=[]; inputs=["rs1c"; "rs2c"]};
  hacky ans "F_MADD_TYPE_S" "FNMSUB_S" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "MVVCOMPRESS" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "F_UN_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  hacky ans "RTYPE" "RISCV_SLT" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "FWVVTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  def ans  "RISCV_FROUND_H" {out=["rd"]; inputs=["rs1"]};
  hacky ans "RTYPE" "RISCV_ADD" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_JAL" {out=["ra"]; inputs=[]};
  def ans  "SFENCE_VMA" {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "NVTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  hacky ans "ITYPE" "RISCV_ANDI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "AES64KS2" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPE" "RISCV_SRA" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "BTYPE" "RISCV_BEQ" 3 {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "NVSTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  hacky ans "ZBB_RTYPE" "RISCV_MINU" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "F_BIN_RM_TYPE_S" "FMUL_S" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBS_RTYPE" "RISCV_BINV" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPE" "RISCV_AND" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "BTYPE" "RISCV_BGE" 3 {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_FROUND_S" {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBB_RTYPE" "RISCV_MAXU" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "NISTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "C_SLLI" {out=["rsd"]; inputs=["rsd"]};
  def ans  "AES32ESMI" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "VXMTYPE" {out=["vd"]; inputs=["vs2"]};
  hacky ans "SHIFTIOP" "RISCV_SRAI" 3 {out=["rd"]; inputs=["rs1"]};
  hacky ans "F_MADD_TYPE_H" "FMADD_H" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "FENCEI" {out=[]; inputs=[]};
  def ans  "RISCV_FROUNDNX_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "VFMVSF" {out=["vd"]; inputs=["vd"]};
  def ans  "MOVETYPEI" {out=["vd"]; inputs=["vd"]};
  hacky ans "RTYPE" "RISCV_OR" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_FLTQ_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VEXT8TYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "C_OR" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  def ans  "C_LW" {out=["rdc"]; inputs=["rsc"]};
  def ans  "FWVFMATYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "C_LWSP" {out=["rd"]; inputs=["sp"]};
  def ans  "C_ADDI16SP" {out=["sp"]; inputs=["sp"]};
  def ans  "SHA512SIG0L" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SM3P0" {out=["rd"]; inputs=["rs1"]};
  def ans  "SM4ED" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "RISCV_FMINM_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "AES64IM" {out=["rd"]; inputs=["rs1"]};
  def ans  "DIVW" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPE" "RISCV_SLTU" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VLRETYPE" {out=["vd"]; inputs=[]};
  def ans  "C_ZEXT_B" {out=["rsdc"]; inputs=["rsdc"]};
  def ans  "C_MV" {out=["rd"]; inputs=["zreg"; "rs2"]};
  def ans  "VIMTYPE" {out=["vd"]; inputs=["vs2"]};
  def ans  "VFMVFS" {out=["rd"]; inputs=["vs2"]};
  def ans  "LOADRES" {out=["rd"]; inputs=["rs1"]};
  hacky ans "RTYPE" "RISCV_SRL" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_CTZ" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_J" {out=["zreg"]; inputs=[]};
  hacky ans "AMO" "AMOMINU" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "AES32ESI" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "RISCV_FMVH_X_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_SLLIUW" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_BEQZ" {out=[]; inputs=["zreg"]};
  hacky ans "F_BIN_RM_TYPE_H" "FDIV_H" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "AMO" "AMOMAX" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPEW" "RISCV_SRLW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SHA512SUM0" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_FMINM_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SHA512SUM0R" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_ADD_HINT" {out=[]; inputs=[]};
  def ans  "REMW" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VFMV" {out=["vd"]; inputs=["vd"]};
  def ans  "RISCV_ZIP" {out=[]; inputs=[]};
  def ans  "C_SEXT_H" {out=["rsdc"]; inputs=["rsdc"]};
  def ans  "SHA512SUM1" {out=["rd"]; inputs=["rs1"]};
  hacky ans "F_BIN_RM_TYPE_S" "FDIV_S" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "CSR" "CSRRW" 4 {out=["rd"]; inputs=["rs1"]};
  def ans  "WMVXTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  hacky ans "F_MADD_TYPE_H" "FNMSUB_H" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "C_LDSP" {out=["rd"]; inputs=["sp"]};
  hacky ans "BTYPE" "RISCV_BGEU" 3 {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_CPOP" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_FSW" {out=[]; inputs=["rsc1"; "rsc2"]};
  def ans  "C_SW" {out=[]; inputs=["rsc1"; "rsc2"]};
  hacky ans "F_BIN_RM_TYPE_H" "FADD_H" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "FWFTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  hacky ans "F_MADD_TYPE_D" "FMADD_D" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "C_SUB" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  def ans  "VFUNARY0" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "FWVTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  hacky ans "F_MADD_TYPE_S" "FMSUB_S" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "RISCV_FROUNDNX_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "SM4KS" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "RISCV_RORIW" {out=["rd"]; inputs=["rs1"]};
  def ans  "SFENCE_W_INVAL" {out=[]; inputs=[]};
  def ans  "C_JR" {out=["zreg"]; inputs=["rs1"]};
  def ans  "NXTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "C_NOT" {out=["rsdc"]; inputs=["rsdc"]};
  hacky ans "F_MADD_TYPE_D" "FNMSUB_D" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  def ans  "MVVTYPE" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  def ans  "C_ADDIW" {out=["rsd"]; inputs=["rsd"]};
  def ans  "C_LD" {out=["rdc"]; inputs=["rsc"]};
  def ans  "FVFMATYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "RISCV_CTZW" {out=["rd"]; inputs=["rs1"]};
  hacky ans "SHIFTIWOP" "RISCV_SRLIW" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_XPERM8" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_FMAXM_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "F_BIN_RM_TYPE_H" "FSUB_H" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBA_RTYPEUW" "RISCV_ADDUW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SHA256SUM0" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_XOR" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  def ans  "VID_V" {out=["vd"]; inputs=["vd"]};
  def ans  "FENCE" {out=[]; inputs=[]};
  def ans  "C_FLWSP" {out=["rd"]; inputs=["sp"]};
  def ans  "STORE" {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_FMINM_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_LUI_HINT" {out=[]; inputs=[]};
  def ans  "VVMCTYPE" {out=["vd"]; inputs=["vs2"; "vs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_S" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VSSEGTYPE" {out=[]; inputs=[]};
  def ans  "SINVAL_VMA" {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "MOVETYPEX" {out=["vd"]; inputs=["vd"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "F_BIN_TYPE_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "ZICOND_RTYPE" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "ZICOND_RTYPE" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBB_RTYPE" "RISCV_ROL" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "AMO" "AMOAND" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_FSDSP" {out=[]; inputs=["sp"; "rs2"]};
  def ans  "C_BNEZ" {out=[]; inputs=["zreg"]};
  def ans  "SRET" {out=[]; inputs=[]};
  def ans  "FWVVMATYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  def ans  "AES64KS1I" {out=["rd"]; inputs=["rs1"]};
  def ans  "STORE_FP" {out=[]; inputs=["rs2"; "rs1"]};
  def ans  "C_JALR" {out=["ra"]; inputs=["rs1"]};
  def ans  "RMVVTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  hacky ans "AMO" "AMOOR" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_CLZW" {out=["rd"]; inputs=["rs1"]};
  def ans  "REM" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_EBREAK" {out=[]; inputs=[]};
  def ans  "FENCE_TSO" {out=[]; inputs=[]};
  hacky ans "ITYPE" "RISCV_SLTI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "SHA512SIG0" {out=["rd"]; inputs=["rs1"]};
  def ans  "AES64ESM" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "RISCV_FLI_S" {out=["rd"]; inputs=[]};
  def ans  "C_SB" {out=[]; inputs=["rs1c"; "rs2c"]};
  def ans  "C_FLDSP" {out=["rd"]; inputs=["sp"]};
  def ans  "C_MV_HINT" {out=[]; inputs=[]};
  def ans  "VFNUNARY0" {out=["vd"]; inputs=["vd"; "vs2"]};
  hacky ans "UTYPE" "RISCV_AUIPC" 2 {out=["rd"]; inputs=[]};
  def ans  "VFWUNARY0" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "MOVETYPEV" {out=["vd"]; inputs=["vd"; "vs1"]};
  hacky ans "ZBB_EXTOP" "RISCV_SEXTH" 2 {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBA_RTYPE" "RISCV_SH2ADD" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VFUNARY1" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "FWVFTYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "RISCV_FCVTMOD_W_D" {out=["rd"]; inputs=["rs1"]};
  def ans  "C_SRLI" {out=["rsd"]; inputs=["rsd"]};
  hacky ans "ZBS_RTYPE" "RISCV_BSET" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "RTYPEW" "RISCV_ADDW" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RFVVTYPE" {out=["vd"]; inputs=[]};
  def ans  "VSRETYPE" {out=[]; inputs=[]};
  hacky ans "ZBB_RTYPE" "RISCV_ORN" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_SLLI_HINT" {out=[]; inputs=[]};
  def ans  "SHA512SIG0H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "WVVTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  def ans  "LOAD_FP" {out=["rd"]; inputs=["rs1"]};
  def ans  "VVMSTYPE" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  def ans  "FVVMATYPE" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  def ans  "AES64DSM" {out=["rd"]; inputs=["rs1"; "rs2"]};
  hacky ans "F_BIN_RM_TYPE_D" "FDIV_D" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VEXT2TYPE" {out=["vd"]; inputs=["vs2"; "vd"]};
  def ans  "URET" {out=[]; inputs=[]};
  def ans  "C_LI" {out=["rd"]; inputs=["zreg"]};
  def ans  "EBREAK" {out=[]; inputs=[]};
  hacky ans "F_BIN_RM_TYPE_D" "FADD_D" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_SRAI" {out=["rsd"]; inputs=["rsd"]};
  hacky ans "SHIFTIOP" "RISCV_SRLI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "C_LUI" {out=["rd"]; inputs=[]};
  def ans  "RISCV_FMVP_D_X" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_LBU" {out=["rdc"]; inputs=["rs1c"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_RM_TYPE_S" {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBB_EXTOP" "RISCV_ZEXTH" 2 {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBB_RTYPE" "RISCV_XNOR" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBB_RTYPE" "RISCV_MIN" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "WMVVTYPE" {out=["vd"]; inputs=["vs2"; "vs1"; "vd"]};
  def ans  "C_ZEXT_H" {out=["rsdc"]; inputs=["rsdc"]};
  def ans  "MULW" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SHA512SIG1L" {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VVCMPTYPE" {out=["vd"]; inputs=["vs2"; "vs1"]};
  def ans  "VLSEGTYPE" {out=["vd"]; inputs=[]};
  def ans  "ILLEGAL" {out=[]; inputs=[]};
  def ans  "SHA256SIG0" {out=["rd"]; inputs=["rs1"]};
  hacky ans "F_BIN_RM_TYPE_D" "FSUB_D" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "RISCV_BREV8" {out=["rd"]; inputs=["rs1"]};
  hacky ans "ZBKB_RTYPE" "RISCV_PACKH" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "AES32DSMI" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "F_UN_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  def ans  "F_UN_TYPE_H" {out=["rd"]; inputs=["rs1"]};
  hacky ans "RTYPE" "RISCV_SUB" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_FSD" {out=[]; inputs=["rsc1"; "rsc2"]};
  hacky ans "F_BIN_RM_TYPE_S" "FSUB_S" 4 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "C_ADDI4SPN" {out=["rdc"]; inputs=["sp"]};
  def ans  "C_ADDW" {out=["rsd"]; inputs=["rsd"; "rs2"]};
  hacky ans "ZBS_IOP" "RISCV_BEXTI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "VVTYPE" {out=["vd"]; inputs=["vd"; "vs2"; "vs1"]};
  hacky ans "F_MADD_TYPE_H" "FNMADD_H" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  hacky ans "ZBS_IOP" "RISCV_BSETI" 3 {out=["rd"]; inputs=["rs1"]};
  def ans  "VCPOP_M" {out=["rd"]; inputs=[]};
  hacky ans "F_MADD_TYPE_H" "FMSUB_H" 5 {out=["rd"]; inputs=["rs3"; "rs2"; "rs1"]};
  hacky ans "AMO" "AMOADD" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "SHA256SIG1" {out=["rd"]; inputs=["rs1"]};
  def ans  "RISCV_FLEQ_H" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "ZBB_RTYPE" "RISCV_ROR" 3 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "VICMPTYPE" {out=["vd"]; inputs=["vs2"]};
  def ans  "MVXTYPE" {out=["vd"]; inputs=["vd"; "vs2"]};
  def ans  "C_FLW" {out=["rdc"]; inputs=["rsc"]};
  def ans  "C_SWSP" {out=[]; inputs=["sp"; "rs2"]};
  def ans  "RISCV_FLTQ_D" {out=["rd"]; inputs=["rs2"; "rs1"]};
  hacky ans "AMO" "AMOMIN" 0 {out=["rd"]; inputs=["rs2"; "rs1"]};
  def ans  "AES64ES" {out=["rd"]; inputs=["rs1"; "rs2"]};
  def ans  "C_SRAI_HINT" {out=[]; inputs=[]};
  def ans  "DIV" {out=["rd"]; inputs=["rs2"; "rs1"]};
  ans
   let lookup_exn = Hash_info.find from6159 let mem = Hash_info.mem from6159 
let from6159_hacky = [ "VMTYPE"; ]

