(* This file was auto generated *)

let mnemonics =
  let ans = Hashtbl.create 2000 in
  Hashtbl.add ans "c.mv.hint.a6" ("C_MV_HINT", []);
  Hashtbl.add ans "vlseg5re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vasub.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "fleq.d" ("RISCV_FLEQ_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "csrrwi" ("CSR", ["rd"; "csr"; "rs1"]);
  Hashtbl.add ans "flt.h" ("F_BIN_TYPE_H____FLT_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "amominu.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amominu.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoadd.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg7ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vadd.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmfle.vf" ("FVFMTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.mv.hint.s2" ("C_MV_HINT", []);
  Hashtbl.add ans "vfnmacc.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.a1" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vfredosum.vs" ("RFVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmulhsu.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "feq.h" ("F_BIN_TYPE_H____FEQ_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.slli.hint.s7." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vloxseg3ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomaxu.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlsseg8e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "aes32dsi" ("AES32DSI", ["rd"; "rs1"; "rs2"; "bs"]);
  Hashtbl.add ans "vlseg6re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "aes64es" ("AES64ES", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsrl.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg4e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.subw" ("C_SUBW", ["rsd"; "rs2"]);
  Hashtbl.add ans "c.swsp" ("C_SWSP", ["rs2"; "uimm"]);
  Hashtbl.add ans "vadc.vvm" ("VVMSTYPE", ["vd"; "vs2"; "vs1"; "v0"]);
  Hashtbl.add ans "vloxseg3ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmsbf.m" ("VMSBF_M", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "bexti" ("ZBS_IOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vsoxseg3ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg4e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amoadd.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmsltu.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.mv.hint.ra" ("C_MV_HINT", []);
  Hashtbl.add ans "amoadd.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fcvt.wu.h" ("F_UN_RM_TYPE_H____FCVT_WU_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vssseg2e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vzext.vf4" ("VEXT4TYPE", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vnsra.wi" ("NISTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vsub.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg8e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "lhu.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "fmul.h" ("F_BIN_RM_TYPE_H", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "vfmacc.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoand.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vslide1down.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "srl" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg8re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "zext.h" ("ZBB_EXTOP", ["rd"; "rs1"]);
  Hashtbl.add ans "c.add.hint.tp" ("C_ADD_HINT", []);
  Hashtbl.add ans "clmulr" ("RISCV_CLMULR", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.addi.hint.t0" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vlseg2e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fmsub.d" ("F_MADD_TYPE_D", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "c.addi.hint.s10" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.sext.b" ("C_SEXT_B", ["rsdc"]);
  Hashtbl.add ans "amoswap.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoor.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fsqrt.d" ("F_UN_RM_TYPE_D____FSQRT_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amomax.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vnsra.wv" ("NVSTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vssub.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "csrrci" ("CSR", ["rd"; "csr"; "rs1"]);
  Hashtbl.add ans "c.lbu" ("C_LBU", ["rdc"; "uimm"; "rs1c"]);
  Hashtbl.add ans "fminm.d" ("RISCV_FMINM_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fltq.s" ("RISCV_FLTQ_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "bseti" ("ZBS_IOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "lb.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vwredsumu.vs" ("RIVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vfncvt.f.xu.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "aes64im" ("AES64IM", ["rd"; "rs1"]);
  Hashtbl.add ans "vsseg5e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "c.mv.hint.a4" ("C_MV_HINT", []);
  Hashtbl.add ans "fround.d" ("RISCV_FROUND_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.addi.hint.a5" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vluxseg7ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "sha512sig1h" ("SHA512SIG1H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.sh" ("C_SH", ["rs1c"; "uimm"; "rs2c"]);
  Hashtbl.add ans "vfwnmsac.vf" ("FWVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoand.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vwmulu.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amoand.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vloxseg2ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vloxseg3ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg7e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vfmsub.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsoxseg4ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.slli.hint.s4." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vdivu.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "fmvp.d.x" ("RISCV_FMVP_D_X", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vmadc.vx" ("VXMCTYPE", ["vd"; "vs2"; "rs1"]);
  Hashtbl.add ans "vle16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "sm3p1" ("SM3P1", ["rd"; "rs1"]);
  Hashtbl.add ans "vmv4r.v" ("VMVRTYPE", ["vd"; "vs2"]);
  Hashtbl.add ans "c.mul" ("C_MUL", ["rsdc"; "rs2c"]);
  Hashtbl.add ans "vloxei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoand.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfncvt.rod.f.f.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "lbu.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vmsbc.vvm" ("VVMTYPE", ["vd"; "vs2"; "vs1"; "v0"]);
  Hashtbl.add ans "fltq.h" ("RISCV_FLTQ_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "amoxor.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.add.hint.t3" ("C_ADD_HINT", []);
  Hashtbl.add ans "vloxseg4ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg6r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "vadd.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "amomax.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "srai" ("SHIFTIOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vsseg3e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "amoand.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsseg3e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.a0" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vsoxseg2ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg2e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vfwadd.wv" ("FWVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg2e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.li" ("C_LI", ["rd"; "imm"]);
  Hashtbl.add ans "minu" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg4re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "flh" ("LOAD_FP", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "amoxor.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.s8." ("C_SLLI_HINT", []);
  Hashtbl.add ans "c.add.hint.s6" ("C_ADD_HINT", []);
  Hashtbl.add ans "amoswap.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fdiv.h" ("F_BIN_RM_TYPE_H", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "fdiv.s" ("F_BIN_RM_TYPE_S", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "lbu" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vmandn.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "vluxseg2ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfncvt.x.f.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vnsrl.wv" ("NVSTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlsseg7e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "fsgnjx.d" ("F_BIN_TYPE_D____FSGNJX_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlsseg5e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.a2" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vlseg8e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.s6." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vfdiv.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "fmv.d.x" ("F_UN_TYPE_D____FMV_D_X", ["rd"; "rs1"]);
  Hashtbl.add ans "lr.b" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vloxseg4ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.add.hint.t5" ("C_ADD_HINT", []);
  Hashtbl.add ans "vlseg5re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "roriw" ("RISCV_RORIW", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vlsseg4e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vse16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "amomax.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfsub.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "bltu" ("BTYPE", ["rs1"; "rs2"; "imm"]);
  Hashtbl.add ans "amoor.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "remw" ("REMW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vredor.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vfmacc.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfcvt.rtz.xu.f.v" ("VFUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "amominu.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmslt.vv" ("VVCMPTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "add" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg2ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoxor.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vloxseg6ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vssseg4e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "addi" ("ITYPE", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "vsoxseg4ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlsseg8e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "ld" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vmacc.vv" ("MVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fsub.h" ("F_BIN_RM_TYPE_H", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "vsoxseg4ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "slliw" ("SHIFTIWOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vsrl.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vwaddu.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "amominu.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sext.h" ("ZBB_EXTOP", ["rd"; "rs1"]);
  Hashtbl.add ans "vlseg8e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vdiv.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vslide1up.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "amoxor.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lr.b.aq" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "amoswap.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sw.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "amominu.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg8ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg5e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "sm4ks" ("SM4KS", ["rd"; "rs1"; "rs2"; "bs"]);
  Hashtbl.add ans "vsuxseg6ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmsbc.vv" ("VVMCTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "fdiv.d" ("F_BIN_RM_TYPE_D", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "vsoxseg2ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomax.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sc.w.aq.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vluxseg4ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vdivu.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vssseg4e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vwadd.wx" ("WXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vluxseg2ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.gp" ("C_ADDI_HINT", []);
  Hashtbl.add ans "sd.aq" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vlseg7e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amomax.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fli.s" ("RISCV_FLI_S", ["rd"; "constantidx"]);
  Hashtbl.add ans "c.mv.hint.fp" ("C_MV_HINT", []);
  Hashtbl.add ans "c.flwsp" ("C_FLWSP", ["rd"; "imm"]);
  Hashtbl.add ans "vredxor.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsoxei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfwmsac.vv" ("FWVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "srliw" ("SHIFTIWOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "c.srli.hint.a4" ("C_SRLI_HINT", []);
  Hashtbl.add ans "amoadd.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amominu.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg6e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amomin.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vwsub.wx" ("WXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vle32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvt.s.d" ("F_UN_RM_TYPE_D____FCVT_S_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.mv.hint.s4" ("C_MV_HINT", []);
  Hashtbl.add ans "vfwcvt.x.f.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "amomaxu.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vloxei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlsseg6e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vfrsub.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vssrl.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsseg2e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vwmaccsu.vv" ("WMVVTYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.slli.hint.zero." ("C_SLLI_HINT", []);
  Hashtbl.add ans "lr.h" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "sh2add.uw" ("ZBA_RTYPEUW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vmxor.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "c.ebreak" ("C_EBREAK", []);
  Hashtbl.add ans "srli" ("SHIFTIOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "c.addi.hint.s4" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vlseg3re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vfadd.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amominu.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmsne.vi" ("VICMPTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "amoadd.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.j" ("C_J", ["imm"]);
  Hashtbl.add ans "sret" ("SRET", []);
  Hashtbl.add ans "vsseg3r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "vfmerge.vfm" ("VFMERGE", ["vd"; "vs2"; "rs1"; "v0"]);
  Hashtbl.add ans "vlseg7re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vlseg8e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vmul.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "fcvt.d.w" ("F_UN_RM_TYPE_D____FCVT_D_W", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amomax.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.addi.hint.zero" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vsoxseg8ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg5e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amoor.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vssseg2e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vfdiv.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg8re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vmv.v.x" ("MOVETYPEX", ["vd"; "rs1"]);
  Hashtbl.add ans "sc.h.aq" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg4ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmv.s.x" ("VMVSX", ["vd"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.t1." ("C_SLLI_HINT", []);
  Hashtbl.add ans "amoor.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmor.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "vminu.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.lui" ("C_LUI", ["rd"; "imm"]);
  Hashtbl.add ans "c.slli.hint.a7." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vor.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsext.vf2" ("VEXT2TYPE", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "fcvt.h.wu" ("F_UN_RM_TYPE_H____FCVT_H_WU", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vfmsub.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "pack" ("ZBKB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vnmsac.vv" ("MVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vluxseg5ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fsgnjx.s" ("F_BIN_TYPE_S____FSGNJX_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.mv.hint.tp" ("C_MV_HINT", []);
  Hashtbl.add ans "lb.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vmadc.vvm" ("VVMTYPE", ["vd"; "vs2"; "vs1"; "v0"]);
  Hashtbl.add ans "vsseg4r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "c.lh" ("C_LH", ["rdc"; "uimm"; "rs1c"]);
  Hashtbl.add ans "sha256sig1" ("SHA256SIG1", ["rd"; "rs1"]);
  Hashtbl.add ans "lr.w" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "sha512sum1r" ("SHA512SUM1R", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "divu" ("DIV", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.slli.hint.s5." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vsext.vf8" ("VEXT8TYPE", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "fence.tso" ("FENCE_TSO", ["pred"; "succ"]);
  Hashtbl.add ans "c.nop.hint." ("C_NOP_HINT", []);
  Hashtbl.add ans "vluxseg6ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fmin.h" ("F_BIN_TYPE_H____FMIN_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "sha512sig0l" ("SHA512SIG0L", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg4e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vmv1r.v" ("VMVRTYPE", ["vd"; "vs2"]);
  Hashtbl.add ans "mulw" ("MULW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsuxseg7ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vloxseg2ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfmsac.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoadd.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.a7" ("C_MV_HINT", []);
  Hashtbl.add ans "fence" ("FENCE", ["pred"; "succ"]);
  Hashtbl.add ans "fminm.h" ("RISCV_FMINM_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vasubu.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vssrl.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "sm3p0" ("SM3P0", ["rd"; "rs1"]);
  Hashtbl.add ans "vsm.v" ("VMTYPE", ["vd_or_vs3"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.gp" ("C_MV_HINT", []);
  Hashtbl.add ans "vssseg8e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "ebreak" ("EBREAK", []);
  Hashtbl.add ans "xori" ("ITYPE", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "vmxnor.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "vlseg5e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvt.s.w" ("F_UN_RM_TYPE_S____FCVT_S_W", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "fsub.s" ("F_BIN_RM_TYPE_S", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "amomin.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg6e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.fsdsp" ("C_FSDSP", ["rs2"; "uimm"]);
  Hashtbl.add ans "vmflt.vv" ("FVVMTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmadc.vxm" ("VXMTYPE", ["vd"; "vs2"; "rs1"; "v0"]);
  Hashtbl.add ans "fsgnj.h" ("F_BIN_TYPE_H____FSGNJ_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "subw" ("RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "unzip" ("RISCV_UNZIP", ["rd"; "rs1"]);
  Hashtbl.add ans "vsuxei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmv.x.s" ("VMVXS", ["rd"; "vs2"]);
  Hashtbl.add ans "fmaxm.h" ("RISCV_FMAXM_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "lr.w.aq" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vluxseg8ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfsgnj.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.sub" ("C_SUB", ["rsd"; "rs2"]);
  Hashtbl.add ans "vsse8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "fcvt.h.d" ("F_UN_RM_TYPE_H____FCVT_H_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "sc.d.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfwcvt.rtz.xu.f.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "amominu.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmsbc.vx" ("VXMCTYPE", ["vd"; "vs2"; "rs1"]);
  Hashtbl.add ans "vwmulu.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vse32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vasub.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amoxor.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lwu.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "lw.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "c.srli.hint.a5" ("C_SRLI_HINT", []);
  Hashtbl.add ans "ror" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg6ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfnmsub.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fmadd.h" ("F_MADD_TYPE_H", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "amoadd.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg6e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vssseg3e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vmadd.vv" ("MVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amominu.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sfence.vma" ("SFENCE_VMA", ["rs1"; "rs2"]);
  Hashtbl.add ans "c.add.hint.s9" ("C_ADD_HINT", []);
  Hashtbl.add ans "sh" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "fadd.d" ("F_BIN_RM_TYPE_D", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "ori" ("ITYPE", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "vloxseg2ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmsbc.vxm" ("VXMTYPE", ["vd"; "vs2"; "rs1"; "v0"]);
  Hashtbl.add ans "vsuxseg6ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsuxseg4ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.beqz" ("C_BEQZ", ["rs"; "imm"]);
  Hashtbl.add ans "vmv.v.i" ("MOVETYPEI", ["vd"; "simm"]);
  Hashtbl.add ans "amoswap.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg5e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vor.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vsseg4e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg2e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amomaxu.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsoxei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "sltiu" ("ITYPE", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "mul" ("MUL", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsseg4e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "andn" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fsub.d" ("F_BIN_RM_TYPE_D", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "amoswap.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vredminu.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amomin.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfredmax.vs" ("RFVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmsleu.vv" ("VVCMPTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vssra.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vloxseg8ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.mv.hint.t3" ("C_MV_HINT", []);
  Hashtbl.add ans "c.mv.hint.a1" ("C_MV_HINT", []);
  Hashtbl.add ans "c.addi.hint.tp" ("C_ADDI_HINT", []);
  Hashtbl.add ans "amoxor.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vssseg4e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "c.lw" ("C_LW", ["rdc"; "rsc"; "uimm"]);
  Hashtbl.add ans "sc.b.aq.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vredsum.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg6e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.lwsp" ("C_LWSP", ["rd"; "uimm"]);
  Hashtbl.add ans "fmul.d" ("F_BIN_RM_TYPE_D", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "c.add.hint.t2" ("C_ADD_HINT", []);
  Hashtbl.add ans "lr.h.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vrsub.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfwcvt.f.xu.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "slt" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "ldu.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "sb.aq.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "c.not" ("C_NOT", ["rsdc"]);
  Hashtbl.add ans "vlseg7re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vloxseg8ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.t5" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vmseq.vi" ("VICMPTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "c.or" ("C_OR", ["rsd"; "rs2"]);
  Hashtbl.add ans "vmerge.vim" ("MASKTYPEI", ["vd"; "vs2"; "simm"; "v0"]);
  Hashtbl.add ans "vfwnmacc.vv" ("FWVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomin.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfclass.v" ("VFUNARY1", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vlsseg8e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "c.srai.hint.a5" ("C_SRAI_HINT", []);
  Hashtbl.add ans "vlsseg5e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amoadd.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg5ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.s2" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.slli" ("C_SLLI", ["rsd"; "shamt"]);
  Hashtbl.add ans "sha512sig0h" ("SHA512SIG0H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "sll" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vmulh.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg7e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "lb.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vfsgnj.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vfmadd.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsetvli" ("VSETVLI", ["rd"; "rs1"]);
  Hashtbl.add ans "fle.s" ("F_BIN_TYPE_S____FLE_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsra.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "amomaxu.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg2ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vluxseg3ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "aes64dsm" ("AES64DSM", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "add.uw" ("ZBA_RTYPEUW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.slli.hint.a6." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vwaddu.wv" ("WVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlsseg3e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vlsseg8e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vmand.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "vslidedown.vi" ("VISG", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "sha256sig0" ("SHA256SIG0", ["rd"; "rs1"]);
  Hashtbl.add ans "vsseg2e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vsoxseg5ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsbc.vvm" ("VVMSTYPE", ["vd"; "vs2"; "vs1"; "v0"]);
  Hashtbl.add ans "clz" ("RISCV_CLZ", ["rd"; "rs1"]);
  Hashtbl.add ans "c.add.hint.a6" ("C_ADD_HINT", []);
  Hashtbl.add ans "vluxseg6ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlsseg3e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "clzw" ("RISCV_CLZW", ["rd"; "rs1"]);
  Hashtbl.add ans "c.add.hint.t4" ("C_ADD_HINT", []);
  Hashtbl.add ans "vwmaccus.vx" ("WMVXTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoor.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lh.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vlsseg2e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "max" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vredmin.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsseg5e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "aes64ds" ("AES64DS", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "beq" ("BTYPE", ["rs1"; "rs2"; "imm"]);
  Hashtbl.add ans "sc.h.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfwadd.vf" ("FWVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vpopc.m" ("VCPOP_M", ["rd"; "vs2"; "vm"]);
  Hashtbl.add ans "amomax.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfwcvt.f.f.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vwaddu.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vredmaxu.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmin.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.s2." ("C_SLLI_HINT", []);
  Hashtbl.add ans "c.add.hint.s7" ("C_ADD_HINT", []);
  Hashtbl.add ans "vfsub.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.srai.hint.a3" ("C_SRAI_HINT", []);
  Hashtbl.add ans "vfcvt.f.xu.v" ("VFUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "amomaxu.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fmvh.x.d" ("RISCV_FMVH_X_D", ["rd"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.a0" ("C_MV_HINT", []);
  Hashtbl.add ans "vle32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.srai.hint.s0" ("C_SRAI_HINT", []);
  Hashtbl.add ans "fmv.w.x" ("F_UN_TYPE_S____FMV_W_X", ["rd"; "rs1"]);
  Hashtbl.add ans "addw" ("RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vaadd.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vmv8r.v" ("VMVRTYPE", ["vd"; "vs2"]);
  Hashtbl.add ans "packh" ("ZBKB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "amomax.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vle8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.fldsp" ("C_FLDSP", ["rd"; "uimm"]);
  Hashtbl.add ans "vluxseg4ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fmv.x.d" ("F_UN_TYPE_D____FMV_X_D", ["rd"; "rs1"]);
  Hashtbl.add ans "vlsseg3e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "froundnx.s" ("RISCV_FROUNDNX_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amoor.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fround.s" ("RISCV_FROUND_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.addi" ("C_ADDI", ["rsd"; "nzi"]);
  Hashtbl.add ans "fle.d" ("F_BIN_TYPE_D____FLE_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vadc.vim" ("VIMSTYPE", ["vd"; "vs2"; "simm"; "v0"]);
  Hashtbl.add ans "vfwcvt.rtz.x.f.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vfnmacc.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.mv.hint.a3" ("C_MV_HINT", []);
  Hashtbl.add ans "vid.v" ("VID_V", ["vd"; "vm"]);
  Hashtbl.add ans "vlre16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vloxseg7ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg2e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vse64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "amomax.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.addi.hint.t4" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vfirst.m" ("VFIRST_M", ["rd"; "vs2"; "vm"]);
  Hashtbl.add ans "amomax.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg3ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "divuw" ("DIVW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "xnor" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.addi.hint.t1" ("C_ADDI_HINT", []);
  Hashtbl.add ans "amomaxu.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "remuw" ("REMW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vfredmin.vs" ("RFVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amoor.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "csrrc" ("CSR", ["rd"; "csr"; "rs1"]);
  Hashtbl.add ans "zip" ("RISCV_ZIP", ["rd"; "rs1"]);
  Hashtbl.add ans "ldu" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vlseg6re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "fsb" ("STORE_FP", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.s10." ("C_SLLI_HINT", []);
  Hashtbl.add ans "csrrsi" ("CSR", ["rd"; "csr"; "rs1"]);
  Hashtbl.add ans "vlseg4e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fle.h" ("F_BIN_TYPE_H____FLE_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsuxseg8ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vluxseg6ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsse16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "c.zext.b" ("C_ZEXT_B", ["rsdc"]);
  Hashtbl.add ans "amoxor.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlsseg6e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amoswap.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vadc.vxm" ("VXMSTYPE", ["vd"; "vs2"; "rs1"; "v0"]);
  Hashtbl.add ans "vlseg7e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvtmod.w.d" ("RISCV_FCVTMOD_W_D", ["rd"; "rs1"]);
  Hashtbl.add ans "fnmadd.s" ("F_MADD_TYPE_S", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "amomax.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vwmaccu.vx" ("WMVXTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vssrl.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vluxseg5ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoadd.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vluxseg8ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "aes32esmi" ("AES32ESMI", ["rd"; "rs1"; "rs2"; "bs"]);
  Hashtbl.add ans "fcvt.s.l" ("F_UN_RM_TYPE_S____FCVT_S_L", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vfwsub.vv" ("FWVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsoxseg7ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "lr.b.aq.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "csrrs" ("CSR", ["rd"; "csr"; "rs1"]);
  Hashtbl.add ans "fsgnj.d" ("F_BIN_TYPE_D____FSGNJ_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg8re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vsaddu.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "c.slli.hint.t6." ("C_SLLI_HINT", []);
  Hashtbl.add ans "c.add.hint.t0" ("C_ADD_HINT", []);
  Hashtbl.add ans "vmsle.vv" ("VVCMPTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vssra.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlsseg6e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vsll.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsoxseg6ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vssra.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsseg5r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "c.add.hint.a1" ("C_ADD_HINT", []);
  Hashtbl.add ans "vloxseg4ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.mv.hint.s1" ("C_MV_HINT", []);
  Hashtbl.add ans "c.addi.hint.s3" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vsseg3e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addiw" ("C_ADDIW", ["rsd"; "imm"]);
  Hashtbl.add ans "vlseg7re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "orc.b" ("RISCV_ORCB", ["rd"; "rs1"]);
  Hashtbl.add ans "sw.aq.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "fsd" ("STORE_FP", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vluxseg2ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amominu.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoand.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsoxseg7ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmseq.vv" ("VVCMPTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vrgatherei16.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.a3" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vmnand.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "divw" ("DIVW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.add.hint.a5" ("C_ADD_HINT", []);
  Hashtbl.add ans "vremu.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsseg8r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "slli.uw" ("RISCV_SLLIUW", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vsuxseg8ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vnmsac.vx" ("MVXMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomaxu.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fmaxm.s" ("RISCV_FMAXM_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vfrec7.v" ("VFUNARY1", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vsra.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg7e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vsoxseg2ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.add.hint.zero" ("C_ADD_HINT", []);
  Hashtbl.add ans "vmsle.vi" ("VICMPTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vluxseg4ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg7e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvt.h.s" ("F_UN_RM_TYPE_H____FCVT_H_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vloxseg7ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vaadd.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "ecall" ("ECALL", []);
  Hashtbl.add ans "vsuxseg4ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.mv.hint.t5" ("C_MV_HINT", []);
  Hashtbl.add ans "amoor.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfmv.v.f" ("VFMV", ["vd"; "rs1"]);
  Hashtbl.add ans "fmin.d" ("F_BIN_TYPE_D____FMIN_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.slli.hint.t2." ("C_SLLI_HINT", []);
  Hashtbl.add ans "c.add.hint.sp" ("C_ADD_HINT", []);
  Hashtbl.add ans "amomin.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.bnez" ("C_BNEZ", ["rs"; "imm"]);
  Hashtbl.add ans "vsuxseg5ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfmin.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "packw" ("ZBKB_PACKW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fnmsub.h" ("F_MADD_TYPE_H", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "fcvt.lu.d" ("F_UN_RM_TYPE_D____FCVT_LU_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.slli.hint.tp." ("C_SLLI_HINT", []);
  Hashtbl.add ans "sra" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg7ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoswap.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lr.w.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vluxei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.t3" ("C_ADDI_HINT", []);
  Hashtbl.add ans "fmv.x.w" ("F_UN_TYPE_S____FMV_X_W", ["rd"; "rs1"]);
  Hashtbl.add ans "c.add.hint.s5" ("C_ADD_HINT", []);
  Hashtbl.add ans "sh.aq" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "c.addw" ("C_ADDW", ["rsd"; "rs2"]);
  Hashtbl.add ans "amoor.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vand.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vwmaccu.vv" ("WMVVTYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fcvt.l.d" ("F_UN_RM_TYPE_D____FCVT_L_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vfwcvt.f.x.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "aes64ks1i" ("AES64KS1I", ["rd"; "rs1"; "rnum"]);
  Hashtbl.add ans "vssseg6e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "binvi" ("ZBS_IOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vlsseg7e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vlseg4e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amoand.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "flw" ("LOAD_FP", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "fclass.h" ("F_UN_TYPE_H____FCLASS_H", ["rd"; "rs1"]);
  Hashtbl.add ans "vsuxseg3ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoor.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfncvt.f.f.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "csrrw" ("CSR", ["rd"; "csr"; "rs1"]);
  Hashtbl.add ans "vrsub.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vlseg3e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.a3." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vwsub.wv" ("WVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg7e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vmacc.vx" ("MVXMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.mv.hint.t0" ("C_MV_HINT", []);
  Hashtbl.add ans "vloxei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "min" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg6ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoxor.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.srai.hint.a0" ("C_SRAI_HINT", []);
  Hashtbl.add ans "c.jalr" ("C_JALR", ["rs1"]);
  Hashtbl.add ans "c.flw" ("C_FLW", ["rdc"; "rsc"; "uimm"]);
  Hashtbl.add ans "czero.eqz" ("ZICOND_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsra.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "lbu.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "sha256sum1" ("SHA256SUM1", ["rd"; "rs1"]);
  Hashtbl.add ans "vfwredosum.vs" ("RFVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg2e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "sc.w.aq" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vnclip.wi" ("NITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vlseg4re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "amoswap.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.srai.hint.a4" ("C_SRAI_HINT", []);
  Hashtbl.add ans "fmv.x.h" ("F_UN_TYPE_H____FMV_X_H", ["rd"; "rs1"]);
  Hashtbl.add ans "bge" ("BTYPE", ["rs1"; "rs2"; "imm"]);
  Hashtbl.add ans "fcvt.w.h" ("F_UN_RM_TYPE_H____FCVT_W_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amomax.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsseg6e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "ldu.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "feq.d" ("F_BIN_TYPE_D____FEQ_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "mulhu" ("MUL", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg6e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fnmadd.h" ("F_MADD_TYPE_H", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "c.slli.hint.t3." ("C_SLLI_HINT", []);
  Hashtbl.add ans "sc.w.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "xor" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsse32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vlseg8e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vssseg7e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vluxei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "sha512sig0" ("SHA512SIG0", ["rd"; "rs1"]);
  Hashtbl.add ans "vmsgtu.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vnsrl.wx" ("NXSTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "rev8" ("RISCV_REV8", ["rd"; "rs1"]);
  Hashtbl.add ans "fmsub.s" ("F_MADD_TYPE_S", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "amomin.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.addi.hint.a4" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vlseg4re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vsuxseg4ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "ld.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vslideup.vi" ("VISG", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vssubu.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsuxei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.add.hint.a3" ("C_ADD_HINT", []);
  Hashtbl.add ans "amoswap.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fsgnj.s" ("F_BIN_TYPE_S____FSGNJ_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg6e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amoand.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.srai.hint.a2" ("C_SRAI_HINT", []);
  Hashtbl.add ans "c.add.hint.s10" ("C_ADD_HINT", []);
  Hashtbl.add ans "vlseg3re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "sh3add.uw" ("ZBA_RTYPEUW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vfwmsac.vf" ("FWVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vssseg8e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amoxor.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "addiw" ("ADDIW", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "vfcvt.xu.f.v" ("VFUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vfmv.s.f" ("VFMVSF", ["vd"; "rs1"]);
  Hashtbl.add ans "vnclipu.wv" ("NVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amoor.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.s8" ("C_MV_HINT", []);
  Hashtbl.add ans "vnclipu.wx" ("NXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsseg7e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "sinval.vma" ("SINVAL_VMA", ["rs1"; "rs2"]);
  Hashtbl.add ans "vmorn.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "fclass.d" ("F_UN_TYPE_D____FCLASS_D", ["rd"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.sp" ("C_MV_HINT", []);
  Hashtbl.add ans "c.ld" ("C_LD", ["rdc"; "rsc"; "uimm"]);
  Hashtbl.add ans "amomaxu.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmsleu.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg8re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vlseg4e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vsseg2e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "sc.h" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsoxseg8ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "clmul" ("RISCV_CLMUL", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "lr.d.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vxor.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "maxu" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "amoswap.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sha512sig1l" ("SHA512SIG1L", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vluxseg3ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "mulh" ("MUL", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg8ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vwsubu.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "fnmsub.s" ("F_MADD_TYPE_S", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "viota.m" ("VIOTA_M", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vsetvl" ("VSETVL", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vse8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "rori" ("RISCV_RORI", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vloxseg7ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fsgnjn.h" ("F_BIN_TYPE_H____FSGNJN_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "sc.d" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg6re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "clmulh" ("RISCV_CLMULH", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fcvt.l.h" ("F_UN_RM_TYPE_H____FCVT_L_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vsseg3e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vmerge.vvm" ("MASKTYPEV", ["vd"; "vs2"; "vs1"; "v0"]);
  Hashtbl.add ans "vfsgnjn.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsll.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vwsub.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlseg5re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vluxseg7ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vzext.vf8" ("VEXT8TYPE", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "c.add.hint.s3" ("C_ADD_HINT", []);
  Hashtbl.add ans "amoor.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoswap.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sub" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vfwnmsac.vv" ("FWVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmulhsu.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vmsof.m" ("VMSOF_M", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vle64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "sb" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "c.sw" ("C_SW", ["rsc1"; "rsc2"; "uimm"]);
  Hashtbl.add ans "amomin.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.gp." ("C_SLLI_HINT", []);
  Hashtbl.add ans "fence.i" ("FENCEI", []);
  Hashtbl.add ans "vmnor.mm" ("MMTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "vfncvt.f.x.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "c.add.hint.t1" ("C_ADD_HINT", []);
  Hashtbl.add ans "fleq.s" ("RISCV_FLEQ_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fround.h" ("RISCV_FROUND_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.mv.hint.zero" ("C_MV_HINT", []);
  Hashtbl.add ans "vsoxseg4ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "auipc" ("UTYPE", ["rd"; "imm"]);
  Hashtbl.add ans "fcvt.wu.s" ("F_UN_RM_TYPE_S____FCVT_WU_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amoxor.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vwadd.wv" ("WVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.a4" ("C_ADD_HINT", []);
  Hashtbl.add ans "sc.h.aq.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg3ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoswap.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vaaddu.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg3e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvt.d.s" ("F_UN_RM_TYPE_D____FCVT_D_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vslidedown.vx" ("VXSG", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.sp." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vsetivli" ("VSETIVLI", ["rd"; "uimm"]);
  Hashtbl.add ans "fcvt.lu.s" ("F_UN_RM_TYPE_S____FCVT_LU_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.add.hint.t6" ("C_ADD_HINT", []);
  Hashtbl.add ans "vmfne.vf" ("FVFMTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "sc.b" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vssseg7e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amoswap.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lw.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vnmsub.vx" ("MVXMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.zext.h" ("C_ZEXT_H", ["rsdc"]);
  Hashtbl.add ans "sb.aq" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "sh1add.uw" ("ZBA_RTYPEUW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fcvt.d.l" ("F_UN_RM_TYPE_D____FCVT_D_L", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "fsw" ("STORE_FP", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vfmul.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vmaxu.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vwredsum.vs" ("RIVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vredand.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmsne.vv" ("VVCMPTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsext.vf4" ("VEXT4TYPE", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "lr.b.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vle64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vsaddu.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "amoadd.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg3re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "c.srli.hint.s1" ("C_SRLI_HINT", []);
  Hashtbl.add ans "xperm4" ("RISCV_XPERM4", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsseg4e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vssseg8e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "bclri" ("ZBS_IOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "vminu.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.s8" ("C_ADDI_HINT", []);
  Hashtbl.add ans "amoadd.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg3e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vfwcvt.xu.f.v" ("VFWUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vssseg5e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "c.slli.hint.a4." ("C_SLLI_HINT", []);
  Hashtbl.add ans "bset" ("ZBS_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg3ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vluxseg5ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.li.hint." ("C_LI_HINT", []);
  Hashtbl.add ans "c.addi4spn" ("C_ADDI4SPN", ["rdc"; "nzimm"]);
  Hashtbl.add ans "vsuxseg6ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "lhu" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vluxseg5ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfcvt.x.f.v" ("VFUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "fcvt.h.l" ("F_UN_RM_TYPE_H____FCVT_H_L", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vlseg2re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "fcvt.lu.h" ("F_UN_RM_TYPE_H____FCVT_LU_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vlseg8e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vnmsub.vv" ("MVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoxor.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg2re8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "sc.d.aq.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vloxei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfmax.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amominu.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg5e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vsoxseg3ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg6e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg5e8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvt.d.lu" ("F_UN_RM_TYPE_D____FCVT_D_LU", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vsbc.vxm" ("VXMSTYPE", ["vd"; "vs2"; "rs1"; "v0"]);
  Hashtbl.add ans "vsseg4e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "amominu.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoxor.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.t0." ("C_SLLI_HINT", []);
  Hashtbl.add ans "c.addi.hint.sp" ("C_ADDI_HINT", []);
  Hashtbl.add ans "srlw" ("RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vrem.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "fsqrt.h" ("F_UN_RM_TYPE_H____FSQRT_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vlre8.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vlseg6e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amoor.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmulhu.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsoxseg8ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsoxei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoor.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vdiv.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vluxei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fcvt.h.lu" ("F_UN_RM_TYPE_H____FCVT_H_LU", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "fcvt.wu.d" ("F_UN_RM_TYPE_D____FCVT_WU_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amominu.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lr.h.aq" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vlseg5e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "lw" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "brev8" ("RISCV_BREV8", ["rd"; "rs1"]);
  Hashtbl.add ans "vfsgnjx.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.mv.hint.s6" ("C_MV_HINT", []);
  Hashtbl.add ans "vfmul.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.and" ("C_AND", ["rsd"; "rs2"]);
  Hashtbl.add ans "vluxseg4ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "sh1add" ("ZBA_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vwadd.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "fmaxm.d" ("RISCV_FMAXM_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "remu" ("REM", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fleq.h" ("RISCV_FLEQ_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.mv.hint.a5" ("C_MV_HINT", []);
  Hashtbl.add ans "vluxseg8ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlsseg2e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "sb.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vssub.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amomaxu.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlsseg4e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vsuxseg7ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "slti" ("ITYPE", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "vlseg8e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vlse16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vwmulsu.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "lb" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vfadd.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfcvt.rtz.x.f.v" ("VFUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "amomaxu.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfwmul.vf" ("FWVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfcvt.f.x.v" ("VFUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vsuxseg5ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "mulhsu" ("MUL", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vredmax.vs" ("RMVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vnsra.wx" ("NXSTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfwmul.vv" ("FWVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "sllw" ("RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg8e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg2e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vssubu.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.fsd" ("C_FSD", ["rsc1"; "rsc2"; "uimm"]);
  Hashtbl.add ans "vsoxseg3ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.s6" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.andi" ("C_ANDI", ["rsd"; "imm"]);
  Hashtbl.add ans "vsoxseg5ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg8e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "sltu" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.srli.hint.s0" ("C_SRLI_HINT", []);
  Hashtbl.add ans "vlseg3e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vfwmacc.vf" ("FWVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg5e64.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vwadd.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfrdiv.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "sw" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "ld.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "amoor.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.t6" ("C_MV_HINT", []);
  Hashtbl.add ans "amoswap.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vaaddu.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.ra" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.mv.hint.t4" ("C_MV_HINT", []);
  Hashtbl.add ans "vlseg7re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "fmul.s" ("F_BIN_RM_TYPE_S", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "c.add.hint.s1" ("C_ADD_HINT", []);
  Hashtbl.add ans "amoxor.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmfeq.vf" ("FVFMTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.sb" ("C_SB", ["rs2c"; "uimm"; "rs1c"]);
  Hashtbl.add ans "lui" ("UTYPE", ["rd"; "imm"]);
  Hashtbl.add ans "aes64ks2" ("AES64KS2", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fli.h" ("RISCV_FLI_H", ["rd"; "constantidx"]);
  Hashtbl.add ans "vmax.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "fltq.d" ("RISCV_FLTQ_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "sha512sig1" ("SHA512SIG1", ["rd"; "rs1"]);
  Hashtbl.add ans "amominu.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlse32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vlseg3re32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vwmulsu.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vmsgtu.vi" ("VICMPTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "fsgnjn.d" ("F_BIN_TYPE_D____FSGNJN_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fsgnjx.h" ("F_BIN_TYPE_H____FSGNJX_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.add" ("C_ADD", ["rsd"; "rs2"]);
  Hashtbl.add ans "vlsseg3e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "rem" ("REM", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg4ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmax.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vslideup.vx" ("VXSG", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.lhu" ("C_LHU", ["rdc"; "uimm"; "rs1c"]);
  Hashtbl.add ans "lh" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vssseg3e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vand.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.t4." ("C_SLLI_HINT", []);
  Hashtbl.add ans "amoand.b.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfwsub.wf" ("FWFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfwmacc.vv" ("FWVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "uret" ("URET", []);
  Hashtbl.add ans "vfmin.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vssseg8e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "fmax.s" ("F_BIN_TYPE_S____FMAX_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "flb" ("LOAD_FP", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "c.addi.hint.s11" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.addi.hint.s1" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vfmax.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vwmacc.vx" ("WMVXTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vwsubu.wx" ("WXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "froundnx.h" ("RISCV_FROUNDNX_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vssseg7e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vloxseg5ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoswap.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsuxseg8ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmin.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "lr.d.aq.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vsseg7e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "amoand.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfwnmacc.vf" ("FWVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vwsubu.wv" ("WVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "czero.nez" ("ZICOND_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vmul.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "lr.d.aq" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vmfle.vv" ("FVVMTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vfncvt.rtz.x.f.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "c.jal" ("C_JAL", ["imm"]);
  Hashtbl.add ans "vfnmsac.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmadc.vim" ("VIMTYPE", ["vd"; "vs2"; "simm"; "v0"]);
  Hashtbl.add ans "vsoxseg6ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfslide1up.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vnsrl.wi" ("NISTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "fcvt.w.s" ("F_UN_RM_TYPE_S____FCVT_W_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vmadc.vi" ("VIMCTYPE", ["vd"; "vs2"; "simm"]);
  Hashtbl.add ans "c.jr" ("C_JR", ["rs1"]);
  Hashtbl.add ans "c.fswsp" ("C_FSWSP", ["rs2"; "uimm"]);
  Hashtbl.add ans "vssseg2e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vadd.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vluxseg3ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmsle.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vxor.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "aes64esm" ("AES64ESM", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsaddu.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "sc.w" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlsseg2e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vwmaccsu.vx" ("WMVXTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "lbu.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "sraiw" ("SHIFTIWOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "c.fsw" ("C_FSW", ["rsc1"; "rsc2"; "uimm"]);
  Hashtbl.add ans "amomin.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmulhu.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vor.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vfsqrt.v" ("VFUNARY1", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "fcvt.h.w" ("F_UN_RM_TYPE_H____FCVT_H_W", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vlse64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vsse64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "fcvt.d.wu" ("F_UN_RM_TYPE_D____FCVT_D_WU", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "c.addi.hint.a7" ("C_ADDI_HINT", []);
  Hashtbl.add ans "sh3add" ("ZBA_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vmfeq.vv" ("FVVMTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "aes32esi" ("AES32ESI", ["rd"; "rs1"; "rs2"; "bs"]);
  Hashtbl.add ans "vmsltu.vv" ("VVCMPTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmadc.vv" ("VVMCTYPE", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "bext" ("ZBS_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.slli.hint.a5." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vfmadd.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.addi.hint.s5" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vsseg6e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addi16sp" ("C_ADDI16SP", ["imm"]);
  Hashtbl.add ans "vwmacc.vv" ("WMVVTYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmfne.vv" ("FVVMTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.ra" ("C_ADD_HINT", []);
  Hashtbl.add ans "vlseg2re16.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "slli" ("SHIFTIOP", ["rd"; "rs1"; "shamt"]);
  Hashtbl.add ans "fmin.s" ("F_BIN_TYPE_S____FMIN_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "jal" ("RISCV_JAL", ["rd"; "imm"]);
  Hashtbl.add ans "vsll.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "vrgather.vx" ("VXSG", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "bgeu" ("BTYPE", ["rs1"; "rs2"; "imm"]);
  Hashtbl.add ans "vsuxseg7ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg3e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vfnmsac.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.lui.hint." ("C_LUI_HINT", []);
  Hashtbl.add ans "c.illegal" ("C_ILLEGAL", ["s"]);
  Hashtbl.add ans "c.mv.hint.s5" ("C_MV_HINT", []);
  Hashtbl.add ans "vfredusum.vs" ("RFVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vsub.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amoor.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.addi.hint.a6" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vsoxseg6ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmerge.vxm" ("MASKTYPEX", ["vd"; "vs2"; "rs1"; "v0"]);
  Hashtbl.add ans "c.slli.hint.s1." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vssseg3e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vlseg7e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.s4" ("C_ADD_HINT", []);
  Hashtbl.add ans "c.srli.hint.a3" ("C_SRLI_HINT", []);
  Hashtbl.add ans "vssseg6e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amominu.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "orn" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "and" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vrgather.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vfsgnjn.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "mret" ("MRET", []);
  Hashtbl.add ans "vmv.v.v" ("MOVETYPEV", ["vd"; "vs1"]);
  Hashtbl.add ans "vluxseg8ei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsuxei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.mv.hint.s7" ("C_MV_HINT", []);
  Hashtbl.add ans "sha512sum0" ("SHA512SUM0", ["rd"; "rs1"]);
  Hashtbl.add ans "c.srai.hint.a1" ("C_SRAI_HINT", []);
  Hashtbl.add ans "ldu.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "c.nop" ("C_NOP", []);
  Hashtbl.add ans "c.mv.hint.s10" ("C_MV_HINT", []);
  Hashtbl.add ans "amoadd.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlsseg2e32.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amomin.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sc.b.rl" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsseg5e64.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.s8" ("C_ADD_HINT", []);
  Hashtbl.add ans "div" ("DIV", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vlseg2e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vfrsqrt7.v" ("VFUNARY1", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg2e64ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg3e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "lh.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "c.srli.hint.a0" ("C_SRLI_HINT", []);
  Hashtbl.add ans "c.slli.hint.ra." ("C_SLLI_HINT", []);
  Hashtbl.add ans "amomin.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lwu.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "c.xor" ("C_XOR", ["rsd"; "rs2"]);
  Hashtbl.add ans "vlseg6re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vrem.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsoxseg5ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfwredusum.vs" ("RFVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vmsne.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.mv.hint.s11" ("C_MV_HINT", []);
  Hashtbl.add ans "lw.aq" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "amomax.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsseg6e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "sh.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "illegal" ("ILLEGAL", ["s"]);
  Hashtbl.add ans "fminm.s" ("RISCV_FMINM_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fadd.h" ("F_BIN_RM_TYPE_H", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "vsseg8e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vsoxseg5ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "sraw" ("RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "aes32dsmi" ("AES32DSMI", ["rd"; "rs1"; "rs2"; "bs"]);
  Hashtbl.add ans "c.add.hint.a7" ("C_ADD_HINT", []);
  Hashtbl.add ans "sd.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vlsseg5e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "fsgnjn.s" ("F_BIN_TYPE_S____FSGNJN_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "fli.d" ("RISCV_FLI_D", ["rd"; "constantidx"]);
  Hashtbl.add ans "vwsubu.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vle16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.s7" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.srli" ("C_SRLI", ["rsd"; "shamt"]);
  Hashtbl.add ans "vluxseg6ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.add.hint.gp" ("C_ADD_HINT", []);
  Hashtbl.add ans "vlsseg7e64.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "fmv.h.x" ("F_UN_TYPE_H____FMV_H_X", ["rd"; "rs1"]);
  Hashtbl.add ans "sc.d.aq" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vmv2r.v" ("VMVRTYPE", ["vd"; "vs2"]);
  Hashtbl.add ans "amomin.b.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vssseg6e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vlse8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vmflt.vf" ("FVFMTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vfmsac.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfslide1down.vf" ("FVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vnclip.wx" ("NXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.a2" ("C_ADD_HINT", []);
  Hashtbl.add ans "jalr" ("RISCV_JALR", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "fld" ("LOAD_FP", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "c.addi.hint.t6" ("C_ADDI_HINT", []);
  Hashtbl.add ans "vmslt.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vloxseg5ei8.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg2re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "c.add.hint.a0" ("C_ADD_HINT", []);
  Hashtbl.add ans "vssseg7e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vssseg4e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vsseg7r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "vssseg5e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vnclipu.wi" ("NITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "sha512sum0r" ("SHA512SUM0R", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "andi" ("ITYPE", ["rd"; "rs1"; "imm"]);
  Hashtbl.add ans "cpop" ("RISCV_CPOP", ["rd"; "rs1"]);
  Hashtbl.add ans "feq.s" ("F_BIN_TYPE_S____FEQ_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vloxseg5ei64.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfmv.f.s" ("VFMVFS", ["rd"; "vs2"]);
  Hashtbl.add ans "vsuxseg6ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfnmsub.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vmseq.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.t2" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.mv" ("C_MV", ["rd"; "rs2"]);
  Hashtbl.add ans "vlsseg4e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "sm4ed" ("SM4ED", ["rd"; "rs1"; "rs2"; "bs"]);
  Hashtbl.add ans "amomax.d.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.mv.hint.a2" ("C_MV_HINT", []);
  Hashtbl.add ans "rolw" ("ZBB_RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "lr.w.aq.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "lr.h.aq.rl" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "vlsseg5e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vssseg6e16.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vle8ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "fclass.s" ("F_UN_TYPE_S____FCLASS_S", ["rd"; "rs1"]);
  Hashtbl.add ans "vmulh.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vlre32.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.s11." ("C_SLLI_HINT", []);
  Hashtbl.add ans "fcvt.d.h" ("F_UN_RM_TYPE_H____FCVT_D_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vmsgt.vi" ("VICMPTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "xperm8" ("RISCV_XPERM8", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.sdsp" ("C_SDSP", ["rs2"; "uimm"]);
  Hashtbl.add ans "blt" ("BTYPE", ["rs1"; "rs2"; "imm"]);
  Hashtbl.add ans "c.zext.w" ("C_ZEXT_W", ["rsdc"]);
  Hashtbl.add ans "c.mv.hint.s9" ("C_MV_HINT", []);
  Hashtbl.add ans "vlseg5e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "sh.aq.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vsoxseg7ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfsgnjx.vv" ("FVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vloxseg6ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.slli.hint.s3." ("C_SLLI_HINT", []);
  Hashtbl.add ans "amoand.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "binv" ("ZBS_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsoxseg3ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsadd.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "lr.d" ("LOADRES", ["rd"; "rs1"]);
  Hashtbl.add ans "lhu.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "wfi" ("WFI", []);
  Hashtbl.add ans "cpopw" ("RISCV_CPOPW", ["rd"; "rs1"]);
  Hashtbl.add ans "amomaxu.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoadd.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.sd" ("C_SD", ["rsc1"; "rsc2"; "uimm"]);
  Hashtbl.add ans "vmaxu.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.srai" ("C_SRAI", ["rsd"; "shamt"]);
  Hashtbl.add ans "vmfgt.vf" ("FVFMTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vsrl.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vloxseg8ei32.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vssseg5e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vfwadd.vv" ("FWVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.fp" ("C_ADD_HINT", []);
  Hashtbl.add ans "flt.s" ("F_BIN_TYPE_S____FLT_S", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "flt.d" ("F_BIN_TYPE_D____FLT_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "sha512sum1" ("SHA512SUM1", ["rd"; "rs1"]);
  Hashtbl.add ans "vand.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "sfence.inval.ir" ("SFENCE_INVAL_IR", []);
  Hashtbl.add ans "c.srai.hint.s1" ("C_SRAI_HINT", []);
  Hashtbl.add ans "vlseg3e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "lhu.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vwaddu.wx" ("WXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.mv.hint.t2" ("C_MV_HINT", []);
  Hashtbl.add ans "vsoxseg8ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsseg8e8.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vlseg3e16.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vsmul.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.fp." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vremu.vv" ("MVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vnclip.wv" ("NVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amoadd.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlseg4e32.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.s11" ("C_ADD_HINT", []);
  Hashtbl.add ans "amomin.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vluxseg3ei8.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfwsub.wv" ("FWVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "amomaxu.h" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amomin.d.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoxor.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vluxseg2ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vfwsub.vf" ("FWVFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "bne" ("BTYPE", ["rs1"; "rs2"; "imm"]);
  Hashtbl.add ans "vssseg5e64.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vfwadd.wf" ("FWFTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "fcvt.s.wu" ("F_UN_RM_TYPE_S____FCVT_S_WU", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "fmax.h" ("F_BIN_TYPE_H____FMAX_H", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsuxseg3ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsuxseg2ei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomaxu.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vfncvt.rtz.xu.f.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "lwu.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vsuxseg2ei8.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "ld.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vlseg7e16ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amomax.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amomax.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vzext.vf2" ("VEXT2TYPE", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "c.srli.hint.a1" ("C_SRLI_HINT", []);
  Hashtbl.add ans "sw.aq" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vsoxseg2ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fadd.s" ("F_BIN_RM_TYPE_S", ["rd"; "rs1"; "rs2"; "rm"]);
  Hashtbl.add ans "c.srli.hint.a2" ("C_SRLI_HINT", []);
  Hashtbl.add ans "vlre64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vsseg7e32.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "sd" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "fnmsub.d" ("F_MADD_TYPE_D", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "fcvt.l.s" ("F_UN_RM_TYPE_S____FCVT_L_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vmadd.vx" ("MVXMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoadd.b.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.a2." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vsmul.vv" ("VVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "vlsseg7e16.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "amomaxu.w.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fsh" ("STORE_FP", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "c.slli.hint.a1." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vsseg2r.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "amoand.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoadd.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vssseg3e8.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vsseg8e16.v" ("VSSEGTYPE", ["vs3"; "rs1"; "vm"]);
  Hashtbl.add ans "vlsseg6e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vmsif.m" ("VMSIF_M", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "ctz" ("RISCV_CTZ", ["rd"; "rs1"]);
  Hashtbl.add ans "vsoxseg6ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "lwu" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vfnmadd.vf" ("FVFMATYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomin.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vcompress.vm" ("MVVCOMPRESS", ["vd"; "vs2"; "vs1"]);
  Hashtbl.add ans "c.slli.hint.a0." ("C_SLLI_HINT", []);
  Hashtbl.add ans "amoand.w.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "sha256sum0" ("SHA256SUM0", ["rd"; "rs1"]);
  Hashtbl.add ans "vrgather.vi" ("VISG", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "fnmadd.d" ("F_MADD_TYPE_D", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "vsr.v" ("VSRETYPE", ["vs3"; "rs1"]);
  Hashtbl.add ans "sd.aq.rl" ("STORE", ["rs2"; "imm"; "rs1"]);
  Hashtbl.add ans "vloxseg5ei16.v" ("VLOXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "fmsub.h" ("F_MADD_TYPE_H", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "vlseg4e32ff.v" ("VLSEGFFTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "amoand.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vlsseg4e8.v" ("VLSSEGTYPE", ["vd"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vfncvt.xu.f.w" ("VFNUNARY0", ["vd"; "vs2"; "vm"]);
  Hashtbl.add ans "vlseg5re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vwmul.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.slli.hint.t5." ("C_SLLI_HINT", []);
  Hashtbl.add ans "vluxei16.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amomin.h.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vluxseg7ei32.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoxor.w.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "c.fld" ("C_FLD", ["rdc"; "rsc"; "uimm"]);
  Hashtbl.add ans "or" ("RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsuxseg2ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsoxei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vsadd.vi" ("VITYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "fcvt.s.h" ("F_UN_RM_TYPE_H____FCVT_S_H", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "amomaxu.d.aq" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "lh.aq.rl" ("LOAD", ["rd"; "imm"; "rs1"]);
  Hashtbl.add ans "vlseg4re64.v" ("VLRETYPE", ["vd"; "rs1"]);
  Hashtbl.add ans "vmfge.vf" ("FVFMTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vluxseg7ei64.v" ("VLUXSEGTYPE", ["vd"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "vlm.v" ("VMTYPE", ["vd_or_vs3"; "rs1"]);
  Hashtbl.add ans "fmadd.s" ("F_MADD_TYPE_S", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "bclr" ("ZBS_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "sfence.w.inval" ("SFENCE_W_INVAL", []);
  Hashtbl.add ans "froundnx.d" ("RISCV_FROUNDNX_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vsoxseg7ei32.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoand.d" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "fmax.d" ("F_BIN_TYPE_D____FMAX_D", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vsuxseg5ei16.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "amoswap.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoxor.b" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "amoand.h.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "rol" ("ZBB_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "rorw" ("ZBB_RTYPEW", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "vasubu.vx" ("MVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "vmsleu.vi" ("VICMPTYPE", ["vd"; "vs2"; "simm"; "vm"]);
  Hashtbl.add ans "fsqrt.s" ("F_UN_RM_TYPE_S____FSQRT_S", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vsuxei64.v" ("VSUXSEGTYPE", ["vs3"; "rs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.sext.h" ("C_SEXT_H", ["rsdc"]);
  Hashtbl.add ans "amominu.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vsadd.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "fmadd.d" ("F_MADD_TYPE_D", ["rd"; "rs1"; "rs2"; "rs3"; "rm"]);
  Hashtbl.add ans "vwmul.vv" ("WVVTYPE", ["vd"; "vs2"; "vs1"; "vm"]);
  Hashtbl.add ans "c.add.hint.s2" ("C_ADD_HINT", []);
  Hashtbl.add ans "c.addi.hint.s9" ("C_ADDI_HINT", []);
  Hashtbl.add ans "amomin.h.aq.rl" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vxor.vx" ("VXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "sext.b" ("ZBB_EXTOP", ["rd"; "rs1"]);
  Hashtbl.add ans "sh2add" ("ZBA_RTYPE", ["rd"; "rs1"; "rs2"]);
  Hashtbl.add ans "c.mv.hint.s3" ("C_MV_HINT", []);
  Hashtbl.add ans "sc.b.aq" ("STORECON", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "vssseg2e32.v" ("VSSSEGTYPE", ["vs3"; "rs1"; "rs2"; "vm"]);
  Hashtbl.add ans "vwsub.vx" ("WVXTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "c.addi.hint.fp" ("C_ADDI_HINT", []);
  Hashtbl.add ans "c.slli.hint.s9." ("C_SLLI_HINT", []);
  Hashtbl.add ans "c.mv.hint.t1" ("C_MV_HINT", []);
  Hashtbl.add ans "vlseg6e8.v" ("VLSEGTYPE", ["vd"; "rs1"; "vm"]);
  Hashtbl.add ans "vmsgt.vx" ("VXCMPTYPE", ["vd"; "vs2"; "rs1"; "vm"]);
  Hashtbl.add ans "amomaxu.w" ("AMO", ["rd"; "rs2"; "rs1"]);
  Hashtbl.add ans "ctzw" ("RISCV_CTZW", ["rd"; "rs1"]);
  Hashtbl.add ans "fcvt.w.d" ("F_UN_RM_TYPE_D____FCVT_W_D", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "fcvt.s.lu" ("F_UN_RM_TYPE_S____FCVT_S_LU", ["rd"; "rs1"; "rm"]);
  Hashtbl.add ans "vfnmadd.vv" ("FVVMATYPE", ["vd"; "vs1"; "vs2"; "vm"]);
  Hashtbl.add ans "c.ldsp" ("C_LDSP", ["rd"; "uimm"]);
  ans
   
let find_opt = Hashtbl.find_opt mnemonics
let find_exn = Hashtbl.find mnemonics
let mem = Hashtbl.mem mnemonics 
