(* This file was auto generated *)
open Instruction

let mnemonics =
  let ans = Hashtbl.create 2000 in
  add_straight ans "c.mv.hint.a6" "C_MV_HINT" [];
  add_straight ans "vlseg5re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vasub.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "fleq.d" "RISCV_FLEQ_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "csrrwi" "CSR" ["rd"; "csr"; "rs1"];
  add_singledef ans "flt.h" "F_BIN_TYPE_H" "FLT_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "amominu.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amominu.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoadd.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg7ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vadd.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmfle.vf" "FVFMTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.mv.hint.s2" "C_MV_HINT" [];
  add_straight ans "vfnmacc.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.a1" "C_ADDI_HINT" [];
  add_straight ans "vfredosum.vs" "RFVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmulhsu.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_singledef ans "feq.h" "F_BIN_TYPE_H" "FEQ_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.slli.hint.s7." "C_SLLI_HINT" [];
  add_straight ans "vloxseg3ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amomaxu.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlsseg8e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "aes32dsi" "AES32DSI" ["rd"; "rs1"; "rs2"; "bs"];
  add_straight ans "vlseg6re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "aes64es" "AES64ES" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsrl.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg4e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.subw" "C_SUBW" ["rsd"; "rs2"];
  add_straight ans "c.swsp" "C_SWSP" ["rs2"; "uimm"];
  add_straight ans "vadc.vvm" "VVMSTYPE" ["vd"; "vs2"; "vs1"; "v0"];
  add_straight ans "vloxseg3ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmsbf.m" "VMSBF_M" ["vd"; "vs2"; "vm"];
  add_straight ans "bexti" "ZBS_IOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "vsoxseg3ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg4e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amoadd.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmsltu.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.mv.hint.ra" "C_MV_HINT" [];
  add_straight ans "amoadd.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_singledef ans "fcvt.wu.h" "F_UN_RM_TYPE_H" "FCVT_WU_H" ["rd"; "rs1"; "rm"];
  add_straight ans "vssseg2e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vzext.vf4" "VEXT4TYPE" ["vd"; "vs2"; "vm"];
  add_straight ans "vnsra.wi" "NISTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vsub.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vlseg8e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "lhu.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "fmul.h" "F_BIN_RM_TYPE_H" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "vfmacc.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "amoand.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vslide1down.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "srl" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg8re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "zext.h" "ZBB_EXTOP" ["rd"; "rs1"];
  add_straight ans "c.add.hint.tp" "C_ADD_HINT" [];
  add_straight ans "clmulr" "RISCV_CLMULR" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.addi.hint.t0" "C_ADDI_HINT" [];
  add_straight ans "vlseg2e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "fmsub.d" "F_MADD_TYPE_D" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "c.addi.hint.s10" "C_ADDI_HINT" [];
  add_straight ans "c.sext.b" "C_SEXT_B" ["rsdc"];
  add_straight ans "amoswap.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoor.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_singledef ans "fsqrt.d" "F_UN_RM_TYPE_D" "FSQRT_D" ["rd"; "rs1"; "rm"];
  add_straight ans "amomax.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vnsra.wv" "NVSTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vssub.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "csrrci" "CSR" ["rd"; "csr"; "rs1"];
  add_straight ans "c.lbu" "C_LBU" ["rdc"; "uimm"; "rs1c"];
  add_straight ans "fminm.d" "RISCV_FMINM_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "fltq.s" "RISCV_FLTQ_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "bseti" "ZBS_IOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "lb.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vwredsumu.vs" "RIVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vfncvt.f.xu.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "aes64im" "AES64IM" ["rd"; "rs1"];
  add_straight ans "vsseg5e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "c.mv.hint.a4" "C_MV_HINT" [];
  add_straight ans "fround.d" "RISCV_FROUND_D" ["rd"; "rs1"; "rm"];
  add_straight ans "c.addi.hint.a5" "C_ADDI_HINT" [];
  add_straight ans "vluxseg7ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "sha512sig1h" "SHA512SIG1H" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.sh" "C_SH" ["rs1c"; "uimm"; "rs2c"];
  add_straight ans "vfwnmsac.vf" "FWVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoand.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vwmulu.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amoand.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vloxseg2ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vloxseg3ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg7e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vfmsub.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsoxseg4ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.slli.hint.s4." "C_SLLI_HINT" [];
  add_straight ans "vdivu.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "fmvp.d.x" "RISCV_FMVP_D_X" ["rd"; "rs1"; "rs2"];
  add_straight ans "vmadc.vx" "VXMCTYPE" ["vd"; "vs2"; "rs1"];
  add_straight ans "vle16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "sm3p1" "SM3P1" ["rd"; "rs1"];
  add_straight ans "vmv4r.v" "VMVRTYPE" ["vd"; "vs2"];
  add_straight ans "c.mul" "C_MUL" ["rsdc"; "rs2c"];
  add_straight ans "vloxei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoand.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfncvt.rod.f.f.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "lbu.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vmsbc.vvm" "VVMTYPE" ["vd"; "vs2"; "vs1"; "v0"];
  add_straight ans "fltq.h" "RISCV_FLTQ_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "amoxor.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.add.hint.t3" "C_ADD_HINT" [];
  add_straight ans "vloxseg4ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg6r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "vadd.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "amomax.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "srai" "SHIFTIOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "vsseg3e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "amoand.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsseg3e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "c.addi.hint.a0" "C_ADDI_HINT" [];
  add_straight ans "vsoxseg2ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg2e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vfwadd.wv" "FWVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg2e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.li" "C_LI" ["rd"; "imm"];
  add_straight ans "minu" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg4re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "flh" "LOAD_FP" ["rd"; "imm"; "rs1"];
  add_straight ans "amoxor.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.slli.hint.s8." "C_SLLI_HINT" [];
  add_straight ans "c.add.hint.s6" "C_ADD_HINT" [];
  add_straight ans "amoswap.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "fdiv.h" "F_BIN_RM_TYPE_H" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "fdiv.s" "F_BIN_RM_TYPE_S" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "lbu" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vmandn.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "vluxseg2ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfncvt.x.f.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vnsrl.wv" "NVSTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlsseg7e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_singledef ans "fsgnjx.d" "F_BIN_TYPE_D" "FSGNJX_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlsseg5e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "c.addi.hint.a2" "C_ADDI_HINT" [];
  add_straight ans "vlseg8e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.slli.hint.s6." "C_SLLI_HINT" [];
  add_straight ans "vfdiv.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_singledef ans "fmv.d.x" "F_UN_TYPE_D" "FMV_D_X" ["rd"; "rs1"];
  add_straight ans "lr.b" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vloxseg4ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.add.hint.t5" "C_ADD_HINT" [];
  add_straight ans "vlseg5re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "roriw" "RISCV_RORIW" ["rd"; "rs1"; "shamt"];
  add_straight ans "vlsseg4e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vse16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "amomax.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfsub.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "bltu" "BTYPE" ["rs1"; "rs2"; "imm"];
  add_straight ans "amoor.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "remw" "REMW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vredor.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vfmacc.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfcvt.rtz.xu.f.v" "VFUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "amominu.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmslt.vv" "VVCMPTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "add" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg2ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoxor.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vloxseg6ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vssseg4e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "addi" "ITYPE" ["rd"; "rs1"; "imm"];
  add_straight ans "vsoxseg4ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlsseg8e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "ld" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vmacc.vv" "MVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "fsub.h" "F_BIN_RM_TYPE_H" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "vsoxseg4ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "slliw" "SHIFTIWOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "vsrl.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vwaddu.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "amominu.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sext.h" "ZBB_EXTOP" ["rd"; "rs1"];
  add_straight ans "vlseg8e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vdiv.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vslide1up.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "amoxor.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lr.b.aq" "LOADRES" ["rd"; "rs1"];
  add_straight ans "amoswap.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sw.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "amominu.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg8ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg5e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "sm4ks" "SM4KS" ["rd"; "rs1"; "rs2"; "bs"];
  add_straight ans "vsuxseg6ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmsbc.vv" "VVMCTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "fdiv.d" "F_BIN_RM_TYPE_D" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "vsoxseg2ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amomax.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sc.w.aq.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vluxseg4ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vdivu.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vssseg4e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vwadd.wx" "WXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vluxseg2ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.gp" "C_ADDI_HINT" [];
  add_straight ans "sd.aq" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "vlseg7e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amomax.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "fli.s" "RISCV_FLI_S" ["rd"; "constantidx"];
  add_straight ans "c.mv.hint.fp" "C_MV_HINT" [];
  add_straight ans "c.flwsp" "C_FLWSP" ["rd"; "imm"];
  add_straight ans "vredxor.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsoxei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfwmsac.vv" "FWVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "srliw" "SHIFTIWOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "c.srli.hint.a4" "C_SRLI_HINT" [];
  add_straight ans "amoadd.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amominu.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg6e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amomin.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vwsub.wx" "WXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vle32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fcvt.s.d" "F_UN_RM_TYPE_D" "FCVT_S_D" ["rd"; "rs1"; "rm"];
  add_straight ans "c.mv.hint.s4" "C_MV_HINT" [];
  add_straight ans "vfwcvt.x.f.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "amomaxu.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vloxei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlsseg6e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vfrsub.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vssrl.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsseg2e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vwmaccsu.vv" "WMVVTYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "c.slli.hint.zero." "C_SLLI_HINT" [];
  add_straight ans "lr.h" "LOADRES" ["rd"; "rs1"];
  add_straight ans "sh2add.uw" "ZBA_RTYPEUW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vmxor.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "c.ebreak" "C_EBREAK" [];
  add_straight ans "srli" "SHIFTIOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "c.addi.hint.s4" "C_ADDI_HINT" [];
  add_straight ans "vlseg3re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vfadd.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amominu.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmsne.vi" "VICMPTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "amoadd.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.j" "C_J" ["imm"];
  add_straight ans "sret" "SRET" [];
  add_straight ans "vsseg3r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "vfmerge.vfm" "VFMERGE" ["vd"; "vs2"; "rs1"; "v0"];
  add_straight ans "vlseg7re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vlseg8e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vmul.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_singledef ans "fcvt.d.w" "F_UN_RM_TYPE_D" "FCVT_D_W" ["rd"; "rs1"; "rm"];
  add_straight ans "amomax.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.addi.hint.zero" "C_ADDI_HINT" [];
  add_straight ans "vsoxseg8ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg5e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amoor.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vssseg2e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vfdiv.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vlseg8re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vmv.v.x" "MOVETYPEX" ["vd"; "rs1"];
  add_straight ans "sc.h.aq" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg4ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmv.s.x" "VMVSX" ["vd"; "rs1"];
  add_straight ans "c.slli.hint.t1." "C_SLLI_HINT" [];
  add_straight ans "amoor.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmor.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "vminu.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.lui" "C_LUI" ["rd"; "imm"];
  add_straight ans "c.slli.hint.a7." "C_SLLI_HINT" [];
  add_straight ans "vor.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsext.vf2" "VEXT2TYPE" ["vd"; "vs2"; "vm"];
  add_singledef ans "fcvt.h.wu" "F_UN_RM_TYPE_H" "FCVT_H_WU" ["rd"; "rs1"; "rm"];
  add_straight ans "vfmsub.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "pack" "ZBKB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vnmsac.vv" "MVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "vluxseg5ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_singledef ans "fsgnjx.s" "F_BIN_TYPE_S" "FSGNJX_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.mv.hint.tp" "C_MV_HINT" [];
  add_straight ans "lb.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vmadc.vvm" "VVMTYPE" ["vd"; "vs2"; "vs1"; "v0"];
  add_straight ans "vsseg4r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "c.lh" "C_LH" ["rdc"; "uimm"; "rs1c"];
  add_straight ans "sha256sig1" "SHA256SIG1" ["rd"; "rs1"];
  add_straight ans "lr.w" "LOADRES" ["rd"; "rs1"];
  add_straight ans "sha512sum1r" "SHA512SUM1R" ["rd"; "rs1"; "rs2"];
  add_straight ans "divu" "DIV" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.slli.hint.s5." "C_SLLI_HINT" [];
  add_straight ans "vsext.vf8" "VEXT8TYPE" ["vd"; "vs2"; "vm"];
  add_straight ans "fence.tso" "FENCE_TSO" ["pred"; "succ"];
  add_straight ans "c.nop.hint." "C_NOP_HINT" [];
  add_straight ans "vluxseg6ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_singledef ans "fmin.h" "F_BIN_TYPE_H" "FMIN_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "sha512sig0l" "SHA512SIG0L" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg4e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vmv1r.v" "VMVRTYPE" ["vd"; "vs2"];
  add_straight ans "mulw" "MULW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsuxseg7ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vloxseg2ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfmsac.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoadd.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.mv.hint.a7" "C_MV_HINT" [];
  add_straight ans "fence" "FENCE" ["pred"; "succ"];
  add_straight ans "fminm.h" "RISCV_FMINM_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "vasubu.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vssrl.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "sm3p0" "SM3P0" ["rd"; "rs1"];
  add_straight ans "vsm.v" "VMTYPE" ["vd_or_vs3"; "rs1"];
  add_straight ans "c.mv.hint.gp" "C_MV_HINT" [];
  add_straight ans "vssseg8e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "ebreak" "EBREAK" [];
  add_straight ans "xori" "ITYPE" ["rd"; "rs1"; "imm"];
  add_straight ans "vmxnor.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "vlseg5e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fcvt.s.w" "F_UN_RM_TYPE_S" "FCVT_S_W" ["rd"; "rs1"; "rm"];
  add_straight ans "fsub.s" "F_BIN_RM_TYPE_S" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "amomin.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg6e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.fsdsp" "C_FSDSP" ["rs2"; "uimm"];
  add_straight ans "vmflt.vv" "FVVMTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmadc.vxm" "VXMTYPE" ["vd"; "vs2"; "rs1"; "v0"];
  add_singledef ans "fsgnj.h" "F_BIN_TYPE_H" "FSGNJ_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "subw" "RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "unzip" "RISCV_UNZIP" ["rd"; "rs1"];
  add_straight ans "vsuxei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmv.x.s" "VMVXS" ["rd"; "vs2"];
  add_straight ans "fmaxm.h" "RISCV_FMAXM_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "lr.w.aq" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vluxseg8ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfsgnj.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.sub" "C_SUB" ["rsd"; "rs2"];
  add_straight ans "vsse8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_singledef ans "fcvt.h.d" "F_UN_RM_TYPE_H" "FCVT_H_D" ["rd"; "rs1"; "rm"];
  add_straight ans "sc.d.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfwcvt.rtz.xu.f.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "amominu.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmsbc.vx" "VXMCTYPE" ["vd"; "vs2"; "rs1"];
  add_straight ans "vwmulu.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vse32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vasub.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amoxor.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lwu.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "lw.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "c.srli.hint.a5" "C_SRLI_HINT" [];
  add_straight ans "ror" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg6ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfnmsub.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "fmadd.h" "F_MADD_TYPE_H" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "amoadd.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg6e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vssseg3e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vmadd.vv" "MVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "amominu.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sfence.vma" "SFENCE_VMA" ["rs1"; "rs2"];
  add_straight ans "c.add.hint.s9" "C_ADD_HINT" [];
  add_straight ans "sh" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "fadd.d" "F_BIN_RM_TYPE_D" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "ori" "ITYPE" ["rd"; "rs1"; "imm"];
  add_straight ans "vloxseg2ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmsbc.vxm" "VXMTYPE" ["vd"; "vs2"; "rs1"; "v0"];
  add_straight ans "vsuxseg6ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsuxseg4ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.beqz" "C_BEQZ" ["rs"; "imm"];
  add_straight ans "vmv.v.i" "MOVETYPEI" ["vd"; "simm"];
  add_straight ans "amoswap.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg5e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vor.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vsseg4e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vlseg2e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amomaxu.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsoxei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "sltiu" "ITYPE" ["rd"; "rs1"; "imm"];
  add_straight ans "mul" "MUL" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsseg4e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "andn" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "fsub.d" "F_BIN_RM_TYPE_D" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "amoswap.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vredminu.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amomin.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfredmax.vs" "RFVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmsleu.vv" "VVCMPTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vssra.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vloxseg8ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.mv.hint.t3" "C_MV_HINT" [];
  add_straight ans "c.mv.hint.a1" "C_MV_HINT" [];
  add_straight ans "c.addi.hint.tp" "C_ADDI_HINT" [];
  add_straight ans "amoxor.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vssseg4e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "c.lw" "C_LW" ["rdc"; "rsc"; "uimm"];
  add_straight ans "sc.b.aq.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vredsum.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg6e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.lwsp" "C_LWSP" ["rd"; "uimm"];
  add_straight ans "fmul.d" "F_BIN_RM_TYPE_D" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "c.add.hint.t2" "C_ADD_HINT" [];
  add_straight ans "lr.h.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vrsub.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfwcvt.f.xu.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "slt" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "ldu.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "sb.aq.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "c.not" "C_NOT" ["rsdc"];
  add_straight ans "vlseg7re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vloxseg8ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.t5" "C_ADDI_HINT" [];
  add_straight ans "vmseq.vi" "VICMPTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "c.or" "C_OR" ["rsd"; "rs2"];
  add_straight ans "vmerge.vim" "MASKTYPEI" ["vd"; "vs2"; "simm"; "v0"];
  add_straight ans "vfwnmacc.vv" "FWVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "amomin.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfclass.v" "VFUNARY1" ["vd"; "vs2"; "vm"];
  add_straight ans "vlsseg8e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "c.srai.hint.a5" "C_SRAI_HINT" [];
  add_straight ans "vlsseg5e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "amoadd.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg5ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.s2" "C_ADDI_HINT" [];
  add_straight ans "c.slli" "C_SLLI" ["rsd"; "shamt"];
  add_straight ans "sha512sig0h" "SHA512SIG0H" ["rd"; "rs1"; "rs2"];
  add_straight ans "sll" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vmulh.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg7e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "lb.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vfsgnj.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vfmadd.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsetvli" "VSETVLI" ["rd"; "rs1"];
  add_singledef ans "fle.s" "F_BIN_TYPE_S" "FLE_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsra.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "amomaxu.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg2ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vluxseg3ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "aes64dsm" "AES64DSM" ["rd"; "rs1"; "rs2"];
  add_straight ans "add.uw" "ZBA_RTYPEUW" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.slli.hint.a6." "C_SLLI_HINT" [];
  add_straight ans "vwaddu.wv" "WVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlsseg3e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vlsseg8e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vmand.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "vslidedown.vi" "VISG" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "sha256sig0" "SHA256SIG0" ["rd"; "rs1"];
  add_straight ans "vsseg2e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vsoxseg5ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsbc.vvm" "VVMSTYPE" ["vd"; "vs2"; "vs1"; "v0"];
  add_straight ans "clz" "RISCV_CLZ" ["rd"; "rs1"];
  add_straight ans "c.add.hint.a6" "C_ADD_HINT" [];
  add_straight ans "vluxseg6ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlsseg3e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "clzw" "RISCV_CLZW" ["rd"; "rs1"];
  add_straight ans "c.add.hint.t4" "C_ADD_HINT" [];
  add_straight ans "vwmaccus.vx" "WMVXTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoor.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lh.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vlsseg2e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "max" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vredmin.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsseg5e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "aes64ds" "AES64DS" ["rd"; "rs1"; "rs2"];
  add_straight ans "beq" "BTYPE" ["rs1"; "rs2"; "imm"];
  add_straight ans "sc.h.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfwadd.vf" "FWVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vpopc.m" "VCPOP_M" ["rd"; "vs2"; "vm"];
  add_straight ans "amomax.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfwcvt.f.f.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vwaddu.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vredmaxu.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmin.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.slli.hint.s2." "C_SLLI_HINT" [];
  add_straight ans "c.add.hint.s7" "C_ADD_HINT" [];
  add_straight ans "vfsub.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.srai.hint.a3" "C_SRAI_HINT" [];
  add_straight ans "vfcvt.f.xu.v" "VFUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "amomaxu.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "fmvh.x.d" "RISCV_FMVH_X_D" ["rd"; "rs1"];
  add_straight ans "c.mv.hint.a0" "C_MV_HINT" [];
  add_straight ans "vle32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.srai.hint.s0" "C_SRAI_HINT" [];
  add_singledef ans "fmv.w.x" "F_UN_TYPE_S" "FMV_W_X" ["rd"; "rs1"];
  add_straight ans "addw" "RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vaadd.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vmv8r.v" "VMVRTYPE" ["vd"; "vs2"];
  add_straight ans "packh" "ZBKB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "amomax.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vle8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.fldsp" "C_FLDSP" ["rd"; "uimm"];
  add_straight ans "vluxseg4ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_singledef ans "fmv.x.d" "F_UN_TYPE_D" "FMV_X_D" ["rd"; "rs1"];
  add_straight ans "vlsseg3e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "froundnx.s" "RISCV_FROUNDNX_S" ["rd"; "rs1"; "rm"];
  add_straight ans "amoor.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "fround.s" "RISCV_FROUND_S" ["rd"; "rs1"; "rm"];
  add_straight ans "c.addi" "C_ADDI" ["rsd"; "nzi"];
  add_singledef ans "fle.d" "F_BIN_TYPE_D" "FLE_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "vadc.vim" "VIMSTYPE" ["vd"; "vs2"; "simm"; "v0"];
  add_straight ans "vfwcvt.rtz.x.f.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vfnmacc.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.mv.hint.a3" "C_MV_HINT" [];
  add_straight ans "vid.v" "VID_V" ["vd"; "vm"];
  add_straight ans "vlre16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vloxseg7ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg2e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vse64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "amomax.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.addi.hint.t4" "C_ADDI_HINT" [];
  add_straight ans "vfirst.m" "VFIRST_M" ["rd"; "vs2"; "vm"];
  add_straight ans "amomax.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg3ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "divuw" "DIVW" ["rd"; "rs1"; "rs2"];
  add_straight ans "xnor" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.addi.hint.t1" "C_ADDI_HINT" [];
  add_straight ans "amomaxu.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "remuw" "REMW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vfredmin.vs" "RFVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amoor.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "csrrc" "CSR" ["rd"; "csr"; "rs1"];
  add_straight ans "zip" "RISCV_ZIP" ["rd"; "rs1"];
  add_straight ans "ldu" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vlseg6re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "fsb" "STORE_FP" ["rs2"; "imm"; "rs1"];
  add_straight ans "c.slli.hint.s10." "C_SLLI_HINT" [];
  add_straight ans "csrrsi" "CSR" ["rd"; "csr"; "rs1"];
  add_straight ans "vlseg4e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fle.h" "F_BIN_TYPE_H" "FLE_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsuxseg8ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vluxseg6ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsse16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "c.zext.b" "C_ZEXT_B" ["rsdc"];
  add_straight ans "amoxor.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlsseg6e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "amoswap.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vadc.vxm" "VXMSTYPE" ["vd"; "vs2"; "rs1"; "v0"];
  add_straight ans "vlseg7e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "fcvtmod.w.d" "RISCV_FCVTMOD_W_D" ["rd"; "rs1"];
  add_straight ans "fnmadd.s" "F_MADD_TYPE_S" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "amomax.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vwmaccu.vx" "WMVXTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vssrl.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vluxseg5ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoadd.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vluxseg8ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "aes32esmi" "AES32ESMI" ["rd"; "rs1"; "rs2"; "bs"];
  add_singledef ans "fcvt.s.l" "F_UN_RM_TYPE_S" "FCVT_S_L" ["rd"; "rs1"; "rm"];
  add_straight ans "vfwsub.vv" "FWVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsoxseg7ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "lr.b.aq.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "csrrs" "CSR" ["rd"; "csr"; "rs1"];
  add_singledef ans "fsgnj.d" "F_BIN_TYPE_D" "FSGNJ_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg8re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vsaddu.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "c.slli.hint.t6." "C_SLLI_HINT" [];
  add_straight ans "c.add.hint.t0" "C_ADD_HINT" [];
  add_straight ans "vmsle.vv" "VVCMPTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vssra.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlsseg6e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vsll.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsoxseg6ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vssra.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsseg5r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "c.add.hint.a1" "C_ADD_HINT" [];
  add_straight ans "vloxseg4ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.mv.hint.s1" "C_MV_HINT" [];
  add_straight ans "c.addi.hint.s3" "C_ADDI_HINT" [];
  add_straight ans "vsseg3e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "c.addiw" "C_ADDIW" ["rsd"; "imm"];
  add_straight ans "vlseg7re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "orc.b" "RISCV_ORCB" ["rd"; "rs1"];
  add_straight ans "sw.aq.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "fsd" "STORE_FP" ["rs2"; "imm"; "rs1"];
  add_straight ans "vluxseg2ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amominu.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoand.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsoxseg7ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmseq.vv" "VVCMPTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vrgatherei16.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.addi.hint.a3" "C_ADDI_HINT" [];
  add_straight ans "vmnand.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "divw" "DIVW" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.add.hint.a5" "C_ADD_HINT" [];
  add_straight ans "vremu.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsseg8r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "slli.uw" "RISCV_SLLIUW" ["rd"; "rs1"; "shamt"];
  add_straight ans "vsuxseg8ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vnmsac.vx" "MVXMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amomaxu.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "fmaxm.s" "RISCV_FMAXM_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "vfrec7.v" "VFUNARY1" ["vd"; "vs2"; "vm"];
  add_straight ans "vsra.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg7e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vsoxseg2ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.add.hint.zero" "C_ADD_HINT" [];
  add_straight ans "vmsle.vi" "VICMPTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vluxseg4ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg7e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fcvt.h.s" "F_UN_RM_TYPE_H" "FCVT_H_S" ["rd"; "rs1"; "rm"];
  add_straight ans "vloxseg7ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vaadd.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "ecall" "ECALL" [];
  add_straight ans "vsuxseg4ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.mv.hint.t5" "C_MV_HINT" [];
  add_straight ans "amoor.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfmv.v.f" "VFMV" ["vd"; "rs1"];
  add_singledef ans "fmin.d" "F_BIN_TYPE_D" "FMIN_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.slli.hint.t2." "C_SLLI_HINT" [];
  add_straight ans "c.add.hint.sp" "C_ADD_HINT" [];
  add_straight ans "amomin.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.bnez" "C_BNEZ" ["rs"; "imm"];
  add_straight ans "vsuxseg5ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfmin.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "packw" "ZBKB_PACKW" ["rd"; "rs1"; "rs2"];
  add_straight ans "fnmsub.h" "F_MADD_TYPE_H" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_singledef ans "fcvt.lu.d" "F_UN_RM_TYPE_D" "FCVT_LU_D" ["rd"; "rs1"; "rm"];
  add_straight ans "c.slli.hint.tp." "C_SLLI_HINT" [];
  add_straight ans "sra" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg7ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoswap.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lr.w.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vluxei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.t3" "C_ADDI_HINT" [];
  add_singledef ans "fmv.x.w" "F_UN_TYPE_S" "FMV_X_W" ["rd"; "rs1"];
  add_straight ans "c.add.hint.s5" "C_ADD_HINT" [];
  add_straight ans "sh.aq" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "c.addw" "C_ADDW" ["rsd"; "rs2"];
  add_straight ans "amoor.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vand.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vwmaccu.vv" "WMVVTYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_singledef ans "fcvt.l.d" "F_UN_RM_TYPE_D" "FCVT_L_D" ["rd"; "rs1"; "rm"];
  add_straight ans "vfwcvt.f.x.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "aes64ks1i" "AES64KS1I" ["rd"; "rs1"; "rnum"];
  add_straight ans "vssseg6e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "binvi" "ZBS_IOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "vlsseg7e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vlseg4e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amoand.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "flw" "LOAD_FP" ["rd"; "imm"; "rs1"];
  add_singledef ans "fclass.h" "F_UN_TYPE_H" "FCLASS_H" ["rd"; "rs1"];
  add_straight ans "vsuxseg3ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoor.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfncvt.f.f.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "csrrw" "CSR" ["rd"; "csr"; "rs1"];
  add_straight ans "vrsub.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vlseg3e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.slli.hint.a3." "C_SLLI_HINT" [];
  add_straight ans "vwsub.wv" "WVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg7e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vmacc.vx" "MVXMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.mv.hint.t0" "C_MV_HINT" [];
  add_straight ans "vloxei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "min" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg6ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoxor.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.srai.hint.a0" "C_SRAI_HINT" [];
  add_straight ans "c.jalr" "C_JALR" ["rs1"];
  add_straight ans "c.flw" "C_FLW" ["rdc"; "rsc"; "uimm"];
  add_straight ans "czero.eqz" "ZICOND_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsra.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "lbu.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "sha256sum1" "SHA256SUM1" ["rd"; "rs1"];
  add_straight ans "vfwredosum.vs" "RFVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg2e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "sc.w.aq" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vnclip.wi" "NITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vlseg4re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "amoswap.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.srai.hint.a4" "C_SRAI_HINT" [];
  add_singledef ans "fmv.x.h" "F_UN_TYPE_H" "FMV_X_H" ["rd"; "rs1"];
  add_straight ans "bge" "BTYPE" ["rs1"; "rs2"; "imm"];
  add_singledef ans "fcvt.w.h" "F_UN_RM_TYPE_H" "FCVT_W_H" ["rd"; "rs1"; "rm"];
  add_straight ans "amomax.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsseg6e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "ldu.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_singledef ans "feq.d" "F_BIN_TYPE_D" "FEQ_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "mulhu" "MUL" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg6e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "fnmadd.h" "F_MADD_TYPE_H" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "c.slli.hint.t3." "C_SLLI_HINT" [];
  add_straight ans "sc.w.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "xor" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsse32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vlseg8e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vssseg7e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vluxei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "sha512sig0" "SHA512SIG0" ["rd"; "rs1"];
  add_straight ans "vmsgtu.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vnsrl.wx" "NXSTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "rev8" "RISCV_REV8" ["rd"; "rs1"];
  add_straight ans "fmsub.s" "F_MADD_TYPE_S" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "amomin.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.addi.hint.a4" "C_ADDI_HINT" [];
  add_straight ans "vlseg4re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vsuxseg4ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "ld.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vslideup.vi" "VISG" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vssubu.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsuxei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.add.hint.a3" "C_ADD_HINT" [];
  add_straight ans "amoswap.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_singledef ans "fsgnj.s" "F_BIN_TYPE_S" "FSGNJ_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg6e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amoand.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.srai.hint.a2" "C_SRAI_HINT" [];
  add_straight ans "c.add.hint.s10" "C_ADD_HINT" [];
  add_straight ans "vlseg3re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "sh3add.uw" "ZBA_RTYPEUW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vfwmsac.vf" "FWVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vssseg8e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "amoxor.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "addiw" "ADDIW" ["rd"; "rs1"; "imm"];
  add_straight ans "vfcvt.xu.f.v" "VFUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vfmv.s.f" "VFMVSF" ["vd"; "rs1"];
  add_straight ans "vnclipu.wv" "NVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amoor.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.mv.hint.s8" "C_MV_HINT" [];
  add_straight ans "vnclipu.wx" "NXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsseg7e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "sinval.vma" "SINVAL_VMA" ["rs1"; "rs2"];
  add_straight ans "vmorn.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_singledef ans "fclass.d" "F_UN_TYPE_D" "FCLASS_D" ["rd"; "rs1"];
  add_straight ans "c.mv.hint.sp" "C_MV_HINT" [];
  add_straight ans "c.ld" "C_LD" ["rdc"; "rsc"; "uimm"];
  add_straight ans "amomaxu.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmsleu.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vlseg8re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vlseg4e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vsseg2e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "sc.h" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsoxseg8ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "clmul" "RISCV_CLMUL" ["rd"; "rs1"; "rs2"];
  add_straight ans "lr.d.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vxor.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "maxu" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "amoswap.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sha512sig1l" "SHA512SIG1L" ["rd"; "rs1"; "rs2"];
  add_straight ans "vluxseg3ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "mulh" "MUL" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg8ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vwsubu.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "fnmsub.s" "F_MADD_TYPE_S" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "viota.m" "VIOTA_M" ["vd"; "vs2"; "vm"];
  add_straight ans "vsetvl" "VSETVL" ["rd"; "rs1"; "rs2"];
  add_straight ans "vse8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "rori" "RISCV_RORI" ["rd"; "rs1"; "shamt"];
  add_straight ans "vloxseg7ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_singledef ans "fsgnjn.h" "F_BIN_TYPE_H" "FSGNJN_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "sc.d" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg6re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "clmulh" "RISCV_CLMULH" ["rd"; "rs1"; "rs2"];
  add_singledef ans "fcvt.l.h" "F_UN_RM_TYPE_H" "FCVT_L_H" ["rd"; "rs1"; "rm"];
  add_straight ans "vsseg3e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vmerge.vvm" "MASKTYPEV" ["vd"; "vs2"; "vs1"; "v0"];
  add_straight ans "vfsgnjn.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsll.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vwsub.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlseg5re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vluxseg7ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vzext.vf8" "VEXT8TYPE" ["vd"; "vs2"; "vm"];
  add_straight ans "c.add.hint.s3" "C_ADD_HINT" [];
  add_straight ans "amoor.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoswap.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sub" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vfwnmsac.vv" "FWVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "vmulhsu.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vmsof.m" "VMSOF_M" ["vd"; "vs2"; "vm"];
  add_straight ans "vle64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "sb" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "c.sw" "C_SW" ["rsc1"; "rsc2"; "uimm"];
  add_straight ans "amomin.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.slli.hint.gp." "C_SLLI_HINT" [];
  add_straight ans "fence.i" "FENCEI" [];
  add_straight ans "vmnor.mm" "MMTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "vfncvt.f.x.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "c.add.hint.t1" "C_ADD_HINT" [];
  add_straight ans "fleq.s" "RISCV_FLEQ_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "fround.h" "RISCV_FROUND_H" ["rd"; "rs1"; "rm"];
  add_straight ans "c.mv.hint.zero" "C_MV_HINT" [];
  add_straight ans "vsoxseg4ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "auipc" "UTYPE" ["rd"; "imm"];
  add_singledef ans "fcvt.wu.s" "F_UN_RM_TYPE_S" "FCVT_WU_S" ["rd"; "rs1"; "rm"];
  add_straight ans "amoxor.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vwadd.wv" "WVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.add.hint.a4" "C_ADD_HINT" [];
  add_straight ans "sc.h.aq.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg3ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoswap.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vaaddu.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vlseg3e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fcvt.d.s" "F_UN_RM_TYPE_D" "FCVT_D_S" ["rd"; "rs1"; "rm"];
  add_straight ans "vslidedown.vx" "VXSG" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.slli.hint.sp." "C_SLLI_HINT" [];
  add_straight ans "vsetivli" "VSETIVLI" ["rd"; "uimm"];
  add_singledef ans "fcvt.lu.s" "F_UN_RM_TYPE_S" "FCVT_LU_S" ["rd"; "rs1"; "rm"];
  add_straight ans "c.add.hint.t6" "C_ADD_HINT" [];
  add_straight ans "vmfne.vf" "FVFMTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "sc.b" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vssseg7e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "amoswap.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lw.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vnmsub.vx" "MVXMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.zext.h" "C_ZEXT_H" ["rsdc"];
  add_straight ans "sb.aq" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "sh1add.uw" "ZBA_RTYPEUW" ["rd"; "rs1"; "rs2"];
  add_singledef ans "fcvt.d.l" "F_UN_RM_TYPE_D" "FCVT_D_L" ["rd"; "rs1"; "rm"];
  add_straight ans "fsw" "STORE_FP" ["rs2"; "imm"; "rs1"];
  add_straight ans "vfmul.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vmaxu.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vwredsum.vs" "RIVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vredand.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmsne.vv" "VVCMPTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsext.vf4" "VEXT4TYPE" ["vd"; "vs2"; "vm"];
  add_straight ans "lr.b.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vle64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vsaddu.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "amoadd.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg3re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "c.srli.hint.s1" "C_SRLI_HINT" [];
  add_straight ans "xperm4" "RISCV_XPERM4" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsseg4e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vssseg8e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "bclri" "ZBS_IOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "vminu.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.addi.hint.s8" "C_ADDI_HINT" [];
  add_straight ans "amoadd.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg3e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vfwcvt.xu.f.v" "VFWUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vssseg5e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "c.slli.hint.a4." "C_SLLI_HINT" [];
  add_straight ans "bset" "ZBS_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg3ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vluxseg5ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.li.hint." "C_LI_HINT" [];
  add_straight ans "c.addi4spn" "C_ADDI4SPN" ["rdc"; "nzimm"];
  add_straight ans "vsuxseg6ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "lhu" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vluxseg5ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfcvt.x.f.v" "VFUNARY0" ["vd"; "vs2"; "vm"];
  add_singledef ans "fcvt.h.l" "F_UN_RM_TYPE_H" "FCVT_H_L" ["rd"; "rs1"; "rm"];
  add_straight ans "vlseg2re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_singledef ans "fcvt.lu.h" "F_UN_RM_TYPE_H" "FCVT_LU_H" ["rd"; "rs1"; "rm"];
  add_straight ans "vlseg8e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vnmsub.vv" "MVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "amoxor.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg2re8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "sc.d.aq.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vloxei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfmax.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amominu.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg5e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vsoxseg3ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg6e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vlseg5e8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fcvt.d.lu" "F_UN_RM_TYPE_D" "FCVT_D_LU" ["rd"; "rs1"; "rm"];
  add_straight ans "vsbc.vxm" "VXMSTYPE" ["vd"; "vs2"; "rs1"; "v0"];
  add_straight ans "vsseg4e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "amominu.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoxor.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.slli.hint.t0." "C_SLLI_HINT" [];
  add_straight ans "c.addi.hint.sp" "C_ADDI_HINT" [];
  add_straight ans "srlw" "RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vrem.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_singledef ans "fsqrt.h" "F_UN_RM_TYPE_H" "FSQRT_H" ["rd"; "rs1"; "rm"];
  add_straight ans "vlre8.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vlseg6e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amoor.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmulhu.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsoxseg8ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsoxei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoor.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vdiv.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vluxei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_singledef ans "fcvt.h.lu" "F_UN_RM_TYPE_H" "FCVT_H_LU" ["rd"; "rs1"; "rm"];
  add_singledef ans "fcvt.wu.d" "F_UN_RM_TYPE_D" "FCVT_WU_D" ["rd"; "rs1"; "rm"];
  add_straight ans "amominu.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lr.h.aq" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vlseg5e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "lw" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "brev8" "RISCV_BREV8" ["rd"; "rs1"];
  add_straight ans "vfsgnjx.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.mv.hint.s6" "C_MV_HINT" [];
  add_straight ans "vfmul.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.and" "C_AND" ["rsd"; "rs2"];
  add_straight ans "vluxseg4ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "sh1add" "ZBA_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vwadd.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "fmaxm.d" "RISCV_FMAXM_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "remu" "REM" ["rd"; "rs1"; "rs2"];
  add_straight ans "fleq.h" "RISCV_FLEQ_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.mv.hint.a5" "C_MV_HINT" [];
  add_straight ans "vluxseg8ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlsseg2e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "sb.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "vssub.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amomaxu.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlsseg4e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vsuxseg7ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "slti" "ITYPE" ["rd"; "rs1"; "imm"];
  add_straight ans "vlseg8e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vlse16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vwmulsu.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "lb" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vfadd.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfcvt.rtz.x.f.v" "VFUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "amomaxu.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfwmul.vf" "FWVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfcvt.f.x.v" "VFUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vsuxseg5ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "mulhsu" "MUL" ["rd"; "rs1"; "rs2"];
  add_straight ans "vredmax.vs" "RMVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vnsra.wx" "NXSTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfwmul.vv" "FWVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "sllw" "RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg8e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vlseg2e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vssubu.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.fsd" "C_FSD" ["rsc1"; "rsc2"; "uimm"];
  add_straight ans "vsoxseg3ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.s6" "C_ADDI_HINT" [];
  add_straight ans "c.andi" "C_ANDI" ["rsd"; "imm"];
  add_straight ans "vsoxseg5ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg8e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "sltu" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.srli.hint.s0" "C_SRLI_HINT" [];
  add_straight ans "vlseg3e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vfwmacc.vf" "FWVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg5e64.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vwadd.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfrdiv.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "sw" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "ld.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "amoor.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.mv.hint.t6" "C_MV_HINT" [];
  add_straight ans "amoswap.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vaaddu.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.addi.hint.ra" "C_ADDI_HINT" [];
  add_straight ans "c.mv.hint.t4" "C_MV_HINT" [];
  add_straight ans "vlseg7re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "fmul.s" "F_BIN_RM_TYPE_S" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "c.add.hint.s1" "C_ADD_HINT" [];
  add_straight ans "amoxor.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmfeq.vf" "FVFMTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.sb" "C_SB" ["rs2c"; "uimm"; "rs1c"];
  add_straight ans "lui" "UTYPE" ["rd"; "imm"];
  add_straight ans "aes64ks2" "AES64KS2" ["rd"; "rs1"; "rs2"];
  add_straight ans "fli.h" "RISCV_FLI_H" ["rd"; "constantidx"];
  add_straight ans "vmax.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "fltq.d" "RISCV_FLTQ_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "sha512sig1" "SHA512SIG1" ["rd"; "rs1"];
  add_straight ans "amominu.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlse32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vlseg3re32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vwmulsu.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vmsgtu.vi" "VICMPTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_singledef ans "fsgnjn.d" "F_BIN_TYPE_D" "FSGNJN_D" ["rd"; "rs1"; "rs2"];
  add_singledef ans "fsgnjx.h" "F_BIN_TYPE_H" "FSGNJX_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.add" "C_ADD" ["rsd"; "rs2"];
  add_straight ans "vlsseg3e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "rem" "REM" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg4ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmax.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vslideup.vx" "VXSG" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.lhu" "C_LHU" ["rdc"; "uimm"; "rs1c"];
  add_straight ans "lh" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vssseg3e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vand.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.slli.hint.t4." "C_SLLI_HINT" [];
  add_straight ans "amoand.b.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfwsub.wf" "FWFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfwmacc.vv" "FWVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "uret" "URET" [];
  add_straight ans "vfmin.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vssseg8e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_singledef ans "fmax.s" "F_BIN_TYPE_S" "FMAX_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "flb" "LOAD_FP" ["rd"; "imm"; "rs1"];
  add_straight ans "c.addi.hint.s11" "C_ADDI_HINT" [];
  add_straight ans "c.addi.hint.s1" "C_ADDI_HINT" [];
  add_straight ans "vfmax.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vwmacc.vx" "WMVXTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vwsubu.wx" "WXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "froundnx.h" "RISCV_FROUNDNX_H" ["rd"; "rs1"; "rm"];
  add_straight ans "vssseg7e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vloxseg5ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoswap.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsuxseg8ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmin.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "lr.d.aq.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vsseg7e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "amoand.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfwnmacc.vf" "FWVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vwsubu.wv" "WVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "czero.nez" "ZICOND_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vmul.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "lr.d.aq" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vmfle.vv" "FVVMTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vfncvt.rtz.x.f.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "c.jal" "C_JAL" ["imm"];
  add_straight ans "vfnmsac.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "vmadc.vim" "VIMTYPE" ["vd"; "vs2"; "simm"; "v0"];
  add_straight ans "vsoxseg6ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfslide1up.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vnsrl.wi" "NISTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_singledef ans "fcvt.w.s" "F_UN_RM_TYPE_S" "FCVT_W_S" ["rd"; "rs1"; "rm"];
  add_straight ans "vmadc.vi" "VIMCTYPE" ["vd"; "vs2"; "simm"];
  add_straight ans "c.jr" "C_JR" ["rs1"];
  add_straight ans "c.fswsp" "C_FSWSP" ["rs2"; "uimm"];
  add_straight ans "vssseg2e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vadd.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vluxseg3ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmsle.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vxor.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "aes64esm" "AES64ESM" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsaddu.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "sc.w" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlsseg2e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vwmaccsu.vx" "WMVXTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "lbu.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "sraiw" "SHIFTIWOP" ["rd"; "rs1"; "shamt"];
  add_straight ans "c.fsw" "C_FSW" ["rsc1"; "rsc2"; "uimm"];
  add_straight ans "amomin.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmulhu.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vor.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vfsqrt.v" "VFUNARY1" ["vd"; "vs2"; "vm"];
  add_singledef ans "fcvt.h.w" "F_UN_RM_TYPE_H" "FCVT_H_W" ["rd"; "rs1"; "rm"];
  add_straight ans "vlse64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vsse64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_singledef ans "fcvt.d.wu" "F_UN_RM_TYPE_D" "FCVT_D_WU" ["rd"; "rs1"; "rm"];
  add_straight ans "c.addi.hint.a7" "C_ADDI_HINT" [];
  add_straight ans "sh3add" "ZBA_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vmfeq.vv" "FVVMTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "aes32esi" "AES32ESI" ["rd"; "rs1"; "rs2"; "bs"];
  add_straight ans "vmsltu.vv" "VVCMPTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmadc.vv" "VVMCTYPE" ["vd"; "vs2"; "vs1"];
  add_straight ans "bext" "ZBS_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.slli.hint.a5." "C_SLLI_HINT" [];
  add_straight ans "vfmadd.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "c.addi.hint.s5" "C_ADDI_HINT" [];
  add_straight ans "vsseg6e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "c.addi16sp" "C_ADDI16SP" ["imm"];
  add_straight ans "vwmacc.vv" "WMVVTYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "vmfne.vv" "FVVMTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.add.hint.ra" "C_ADD_HINT" [];
  add_straight ans "vlseg2re16.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "slli" "SHIFTIOP" ["rd"; "rs1"; "shamt"];
  add_singledef ans "fmin.s" "F_BIN_TYPE_S" "FMIN_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "jal" "RISCV_JAL" ["rd"; "imm"];
  add_straight ans "vsll.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "vrgather.vx" "VXSG" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "bgeu" "BTYPE" ["rs1"; "rs2"; "imm"];
  add_straight ans "vsuxseg7ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg3e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vfnmsac.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.lui.hint." "C_LUI_HINT" [];
  add_straight ans "c.illegal" "C_ILLEGAL" ["s"];
  add_straight ans "c.mv.hint.s5" "C_MV_HINT" [];
  add_straight ans "vfredusum.vs" "RFVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vsub.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amoor.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.addi.hint.a6" "C_ADDI_HINT" [];
  add_straight ans "vsoxseg6ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vmerge.vxm" "MASKTYPEX" ["vd"; "vs2"; "rs1"; "v0"];
  add_straight ans "c.slli.hint.s1." "C_SLLI_HINT" [];
  add_straight ans "vssseg3e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vlseg7e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.add.hint.s4" "C_ADD_HINT" [];
  add_straight ans "c.srli.hint.a3" "C_SRLI_HINT" [];
  add_straight ans "vssseg6e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "amominu.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "orn" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "and" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vrgather.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vfsgnjn.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "mret" "MRET" [];
  add_straight ans "vmv.v.v" "MOVETYPEV" ["vd"; "vs1"];
  add_straight ans "vluxseg8ei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsuxei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.mv.hint.s7" "C_MV_HINT" [];
  add_straight ans "sha512sum0" "SHA512SUM0" ["rd"; "rs1"];
  add_straight ans "c.srai.hint.a1" "C_SRAI_HINT" [];
  add_straight ans "ldu.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "c.nop" "C_NOP" [];
  add_straight ans "c.mv.hint.s10" "C_MV_HINT" [];
  add_straight ans "amoadd.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlsseg2e32.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "amomin.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sc.b.rl" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsseg5e64.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "c.add.hint.s8" "C_ADD_HINT" [];
  add_straight ans "div" "DIV" ["rd"; "rs1"; "rs2"];
  add_straight ans "vlseg2e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vfrsqrt7.v" "VFUNARY1" ["vd"; "vs2"; "vm"];
  add_straight ans "vlseg2e64ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vlseg3e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "lh.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "c.srli.hint.a0" "C_SRLI_HINT" [];
  add_straight ans "c.slli.hint.ra." "C_SLLI_HINT" [];
  add_straight ans "amomin.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lwu.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "c.xor" "C_XOR" ["rsd"; "rs2"];
  add_straight ans "vlseg6re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vrem.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsoxseg5ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfwredusum.vs" "RFVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vmsne.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.mv.hint.s11" "C_MV_HINT" [];
  add_straight ans "lw.aq" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "amomax.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsseg6e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "sh.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "illegal" "ILLEGAL" ["s"];
  add_straight ans "fminm.s" "RISCV_FMINM_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "fadd.h" "F_BIN_RM_TYPE_H" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "vsseg8e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vsoxseg5ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "sraw" "RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "aes32dsmi" "AES32DSMI" ["rd"; "rs1"; "rs2"; "bs"];
  add_straight ans "c.add.hint.a7" "C_ADD_HINT" [];
  add_straight ans "sd.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "vlsseg5e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_singledef ans "fsgnjn.s" "F_BIN_TYPE_S" "FSGNJN_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "fli.d" "RISCV_FLI_D" ["rd"; "constantidx"];
  add_straight ans "vwsubu.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vle16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.addi.hint.s7" "C_ADDI_HINT" [];
  add_straight ans "c.srli" "C_SRLI" ["rsd"; "shamt"];
  add_straight ans "vluxseg6ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.add.hint.gp" "C_ADD_HINT" [];
  add_straight ans "vlsseg7e64.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_singledef ans "fmv.h.x" "F_UN_TYPE_H" "FMV_H_X" ["rd"; "rs1"];
  add_straight ans "sc.d.aq" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vmv2r.v" "VMVRTYPE" ["vd"; "vs2"];
  add_straight ans "amomin.b.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vssseg6e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vlse8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vmflt.vf" "FVFMTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vfmsac.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "vfslide1down.vf" "FVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vnclip.wx" "NXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.add.hint.a2" "C_ADD_HINT" [];
  add_straight ans "jalr" "RISCV_JALR" ["rd"; "imm"; "rs1"];
  add_straight ans "fld" "LOAD_FP" ["rd"; "imm"; "rs1"];
  add_straight ans "c.addi.hint.t6" "C_ADDI_HINT" [];
  add_straight ans "vmslt.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vloxseg5ei8.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlseg2re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "c.add.hint.a0" "C_ADD_HINT" [];
  add_straight ans "vssseg7e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vssseg4e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vsseg7r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "vssseg5e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vnclipu.wi" "NITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "sha512sum0r" "SHA512SUM0R" ["rd"; "rs1"; "rs2"];
  add_straight ans "andi" "ITYPE" ["rd"; "rs1"; "imm"];
  add_straight ans "cpop" "RISCV_CPOP" ["rd"; "rs1"];
  add_singledef ans "feq.s" "F_BIN_TYPE_S" "FEQ_S" ["rd"; "rs1"; "rs2"];
  add_straight ans "vloxseg5ei64.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfmv.f.s" "VFMVFS" ["rd"; "vs2"];
  add_straight ans "vsuxseg6ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfnmsub.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "vmseq.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.addi.hint.t2" "C_ADDI_HINT" [];
  add_straight ans "c.mv" "C_MV" ["rd"; "rs2"];
  add_straight ans "vlsseg4e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "sm4ed" "SM4ED" ["rd"; "rs1"; "rs2"; "bs"];
  add_straight ans "amomax.d.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.mv.hint.a2" "C_MV_HINT" [];
  add_straight ans "rolw" "ZBB_RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "lr.w.aq.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "lr.h.aq.rl" "LOADRES" ["rd"; "rs1"];
  add_straight ans "vlsseg5e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vssseg6e16.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vle8ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_singledef ans "fclass.s" "F_UN_TYPE_S" "FCLASS_S" ["rd"; "rs1"];
  add_straight ans "vmulh.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vlre32.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "c.slli.hint.s11." "C_SLLI_HINT" [];
  add_singledef ans "fcvt.d.h" "F_UN_RM_TYPE_H" "FCVT_D_H" ["rd"; "rs1"; "rm"];
  add_straight ans "vmsgt.vi" "VICMPTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "xperm8" "RISCV_XPERM8" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.sdsp" "C_SDSP" ["rs2"; "uimm"];
  add_straight ans "blt" "BTYPE" ["rs1"; "rs2"; "imm"];
  add_straight ans "c.zext.w" "C_ZEXT_W" ["rsdc"];
  add_straight ans "c.mv.hint.s9" "C_MV_HINT" [];
  add_straight ans "vlseg5e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "sh.aq.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "vsoxseg7ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfsgnjx.vv" "FVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vloxseg6ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.slli.hint.s3." "C_SLLI_HINT" [];
  add_straight ans "amoand.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "binv" "ZBS_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsoxseg3ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsadd.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "lr.d" "LOADRES" ["rd"; "rs1"];
  add_straight ans "lhu.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "wfi" "WFI" [];
  add_straight ans "cpopw" "RISCV_CPOPW" ["rd"; "rs1"];
  add_straight ans "amomaxu.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoadd.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.sd" "C_SD" ["rsc1"; "rsc2"; "uimm"];
  add_straight ans "vmaxu.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.srai" "C_SRAI" ["rsd"; "shamt"];
  add_straight ans "vmfgt.vf" "FVFMTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vsrl.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vloxseg8ei32.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vssseg5e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vfwadd.vv" "FWVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.add.hint.fp" "C_ADD_HINT" [];
  add_singledef ans "flt.s" "F_BIN_TYPE_S" "FLT_S" ["rd"; "rs1"; "rs2"];
  add_singledef ans "flt.d" "F_BIN_TYPE_D" "FLT_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "sha512sum1" "SHA512SUM1" ["rd"; "rs1"];
  add_straight ans "vand.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "sfence.inval.ir" "SFENCE_INVAL_IR" [];
  add_straight ans "c.srai.hint.s1" "C_SRAI_HINT" [];
  add_straight ans "vlseg3e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "lhu.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vwaddu.wx" "WXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.mv.hint.t2" "C_MV_HINT" [];
  add_straight ans "vsoxseg8ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsseg8e8.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vlseg3e16.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vsmul.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.slli.hint.fp." "C_SLLI_HINT" [];
  add_straight ans "vremu.vv" "MVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vnclip.wv" "NVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amoadd.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlseg4e32.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "c.add.hint.s11" "C_ADD_HINT" [];
  add_straight ans "amomin.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vluxseg3ei8.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfwsub.wv" "FWVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "amomaxu.h" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amomin.d.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoxor.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vluxseg2ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vfwsub.vf" "FWVFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "bne" "BTYPE" ["rs1"; "rs2"; "imm"];
  add_straight ans "vssseg5e64.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vfwadd.wf" "FWFTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_singledef ans "fcvt.s.wu" "F_UN_RM_TYPE_S" "FCVT_S_WU" ["rd"; "rs1"; "rm"];
  add_singledef ans "fmax.h" "F_BIN_TYPE_H" "FMAX_H" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsuxseg3ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsuxseg2ei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amomaxu.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vfncvt.rtz.xu.f.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "lwu.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vsuxseg2ei8.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "ld.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vlseg7e16ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amomax.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amomax.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vzext.vf2" "VEXT2TYPE" ["vd"; "vs2"; "vm"];
  add_straight ans "c.srli.hint.a1" "C_SRLI_HINT" [];
  add_straight ans "sw.aq" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "vsoxseg2ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "fadd.s" "F_BIN_RM_TYPE_S" ["rd"; "rs1"; "rs2"; "rm"];
  add_straight ans "c.srli.hint.a2" "C_SRLI_HINT" [];
  add_straight ans "vlre64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vsseg7e32.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "sd" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "fnmsub.d" "F_MADD_TYPE_D" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_singledef ans "fcvt.l.s" "F_UN_RM_TYPE_S" "FCVT_L_S" ["rd"; "rs1"; "rm"];
  add_straight ans "vmadd.vx" "MVXMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoadd.b.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.slli.hint.a2." "C_SLLI_HINT" [];
  add_straight ans "vsmul.vv" "VVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "vlsseg7e16.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "amomaxu.w.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "fsh" "STORE_FP" ["rs2"; "imm"; "rs1"];
  add_straight ans "c.slli.hint.a1." "C_SLLI_HINT" [];
  add_straight ans "vsseg2r.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "amoand.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoadd.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vssseg3e8.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vsseg8e16.v" "VSSEGTYPE" ["vs3"; "rs1"; "vm"];
  add_straight ans "vlsseg6e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vmsif.m" "VMSIF_M" ["vd"; "vs2"; "vm"];
  add_straight ans "ctz" "RISCV_CTZ" ["rd"; "rs1"];
  add_straight ans "vsoxseg6ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "lwu" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vfnmadd.vf" "FVFMATYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amomin.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vcompress.vm" "MVVCOMPRESS" ["vd"; "vs2"; "vs1"];
  add_straight ans "c.slli.hint.a0." "C_SLLI_HINT" [];
  add_straight ans "amoand.w.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "sha256sum0" "SHA256SUM0" ["rd"; "rs1"];
  add_straight ans "vrgather.vi" "VISG" ["vd"; "vs2"; "simm"; "vm"];
  add_straight ans "fnmadd.d" "F_MADD_TYPE_D" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "vsr.v" "VSRETYPE" ["vs3"; "rs1"];
  add_straight ans "sd.aq.rl" "STORE" ["rs2"; "imm"; "rs1"];
  add_straight ans "vloxseg5ei16.v" "VLOXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "fmsub.h" "F_MADD_TYPE_H" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "vlseg4e32ff.v" "VLSEGFFTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "amoand.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vlsseg4e8.v" "VLSSEGTYPE" ["vd"; "rs1"; "rs2"; "vm"];
  add_straight ans "vfncvt.xu.f.w" "VFNUNARY0" ["vd"; "vs2"; "vm"];
  add_straight ans "vlseg5re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vwmul.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.slli.hint.t5." "C_SLLI_HINT" [];
  add_straight ans "vluxei16.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amomin.h.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vluxseg7ei32.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoxor.w.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "c.fld" "C_FLD" ["rdc"; "rsc"; "uimm"];
  add_straight ans "or" "RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsuxseg2ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsoxei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "vsadd.vi" "VITYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_singledef ans "fcvt.s.h" "F_UN_RM_TYPE_H" "FCVT_S_H" ["rd"; "rs1"; "rm"];
  add_straight ans "amomaxu.d.aq" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "lh.aq.rl" "LOAD" ["rd"; "imm"; "rs1"];
  add_straight ans "vlseg4re64.v" "VLRETYPE" ["vd"; "rs1"];
  add_straight ans "vmfge.vf" "FVFMTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vluxseg7ei64.v" "VLUXSEGTYPE" ["vd"; "rs1"; "vs2"; "vm"];
  add_straight ans "vlm.v" "VMTYPE" ["vd_or_vs3"; "rs1"];
  add_straight ans "fmadd.s" "F_MADD_TYPE_S" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "bclr" "ZBS_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "sfence.w.inval" "SFENCE_W_INVAL" [];
  add_straight ans "froundnx.d" "RISCV_FROUNDNX_D" ["rd"; "rs1"; "rm"];
  add_straight ans "vsoxseg7ei32.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoand.d" "AMO" ["rd"; "rs2"; "rs1"];
  add_singledef ans "fmax.d" "F_BIN_TYPE_D" "FMAX_D" ["rd"; "rs1"; "rs2"];
  add_straight ans "vsuxseg5ei16.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "amoswap.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoxor.b" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "amoand.h.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "rol" "ZBB_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "rorw" "ZBB_RTYPEW" ["rd"; "rs1"; "rs2"];
  add_straight ans "vasubu.vx" "MVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "vmsleu.vi" "VICMPTYPE" ["vd"; "vs2"; "simm"; "vm"];
  add_singledef ans "fsqrt.s" "F_UN_RM_TYPE_S" "FSQRT_S" ["rd"; "rs1"; "rm"];
  add_straight ans "vsuxei64.v" "VSUXSEGTYPE" ["vs3"; "rs1"; "vs2"; "vm"];
  add_straight ans "c.sext.h" "C_SEXT_H" ["rsdc"];
  add_straight ans "amominu.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vsadd.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "fmadd.d" "F_MADD_TYPE_D" ["rd"; "rs1"; "rs2"; "rs3"; "rm"];
  add_straight ans "vwmul.vv" "WVVTYPE" ["vd"; "vs2"; "vs1"; "vm"];
  add_straight ans "c.add.hint.s2" "C_ADD_HINT" [];
  add_straight ans "c.addi.hint.s9" "C_ADDI_HINT" [];
  add_straight ans "amomin.h.aq.rl" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "vxor.vx" "VXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "sext.b" "ZBB_EXTOP" ["rd"; "rs1"];
  add_straight ans "sh2add" "ZBA_RTYPE" ["rd"; "rs1"; "rs2"];
  add_straight ans "c.mv.hint.s3" "C_MV_HINT" [];
  add_straight ans "sc.b.aq" "STORECON" ["rd"; "rs2"; "rs1"];
  add_straight ans "vssseg2e32.v" "VSSSEGTYPE" ["vs3"; "rs1"; "rs2"; "vm"];
  add_straight ans "vwsub.vx" "WVXTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "c.addi.hint.fp" "C_ADDI_HINT" [];
  add_straight ans "c.slli.hint.s9." "C_SLLI_HINT" [];
  add_straight ans "c.mv.hint.t1" "C_MV_HINT" [];
  add_straight ans "vlseg6e8.v" "VLSEGTYPE" ["vd"; "rs1"; "vm"];
  add_straight ans "vmsgt.vx" "VXCMPTYPE" ["vd"; "vs2"; "rs1"; "vm"];
  add_straight ans "amomaxu.w" "AMO" ["rd"; "rs2"; "rs1"];
  add_straight ans "ctzw" "RISCV_CTZW" ["rd"; "rs1"];
  add_singledef ans "fcvt.w.d" "F_UN_RM_TYPE_D" "FCVT_W_D" ["rd"; "rs1"; "rm"];
  add_singledef ans "fcvt.s.lu" "F_UN_RM_TYPE_S" "FCVT_S_LU" ["rd"; "rs1"; "rm"];
  add_straight ans "vfnmadd.vv" "FVVMATYPE" ["vd"; "vs1"; "vs2"; "vm"];
  add_straight ans "c.ldsp" "C_LDSP" ["rd"; "uimm"];
  ans
   
let find_opt = Hashtbl.find_opt mnemonics
let find_exn = Hashtbl.find mnemonics
let mem = Hashtbl.mem mnemonics 
